### ISSUE TITLE
rpi_camera 'Image not available' on hassos

### ISSUE THREAD

**Issue by imago54** [home-assistant/supervisor#1474]
RPi camera integration on hassos is not working for two years already.
It would be nice if you could make it clear in https://www.home-assistant.io/integrations/rpi_camera/ that **rpi_camera is not working with recommended RPi installation (hassos)**. A lot of people is wasting their time trying to figure out what is going on, while it is well known that on hassos it is not working for such long time.

**Comment by pvizeli** [comment]
Yeah, it did not work because no one with hardware has the knowledge to fix it on the root :(

**Comment by imago54** [comment]
Well, if that's so simple why start_x.elf is not included in /boot partition of hassos?

**Comment by imago54** [comment]
So, I took https://github.com/raspberrypi/firmware/raw/master/boot/start_x.elf
put it in /boot, changed config.txt adding start_x=1 and gpu_mem=128, but it doesn't boot at all.

**Comment by cobaltway** [comment]
I tried to walk on your footsteps with my pi4 by adding the following lines:
```
start_file=start4x.elf
fixup_file=fixup4x.dat
```
But it does not boot (colored screen). Has anyone been more lucky than me?

I've bought this hardware because I saw that there was a RPI integration... if it is not possible to actually use it with the standard install, I also believe this should be explicitly stated.
