### ISSUE TITLE
CoreDNS keeps crashing

### ISSUE THREAD

**Issue by ibBogdan** [home-assistant/supervisor#1615]
**Home Assistant release with the issue:**
arch: aarch64
channel: stable
hassos: "3.12"
homeassistant: 0.107.7
hostname: homeassistant
logging: info
machine: raspberrypi3-64
supervisor: "213"
supported_arch:
- aarch64
- armv7
- armhf

**Supervisor logs:**
20-03-30 06:36:16 INFO (SyncWorker_16) [supervisor.docker.dns] Start DNS homeassistant/aarch64-hassio-dns with version 1 - 172.30.32.3
20-03-30 06:36:16 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-30 06:36:16 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-30 06:36:16 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-30 06:36:16 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_dns application
20-03-30 06:36:30 INFO (SyncWorker_5) [supervisor.docker.dns] Start DNS homeassistant/aarch64-hassio-dns with version 1 - 172.30.32.3

/ $ ha dns logs --log-level Verb
/config/corefile:16 - Error during parsing: Unknown directive 'fallback'

**Description of problem:**
After HASSio supervisor got updated yesterday, COREdns keeps crashing
ha dns logs show nothing

**Comment by aleksandrov1995** [comment]
I do have the same problem on amd64 arch:

20-03-30 07:35:35 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-03-30 07:35:35 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
20-03-30 07:35:35 INFO (MainThread) [supervisor.dns] Start CoreDNS plugin
20-03-30 07:35:35 INFO (SyncWorker_6) [supervisor.docker.interface] Clean hassio_dns application
20-03-30 07:35:39 INFO (SyncWorker_6) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3

Also i do experience issues with the maridb addon, which i believe is because of this. 
The error there is :  "Unknown MySQL server host 'core-mariadb' (-3)")

**Comment by pvizeli** [comment]
use: `ha dns update --version 3`

**Comment by aleksandrov1995** [comment]
Thats what i got:
![image](https://user-images.githubusercontent.com/12535078/77887473-4e60e580-7273-11ea-89b4-ad6d3b90430c.png)

**Comment by pvizeli** [comment]
sounds like the host was not able to sync the time ntp? Or just docker hub have again an issue which is pretty oft happening at last. We need rethinking to use the docker hub soon as possible.

**Comment by aleksandrov1995** [comment]
Its not NPT issue, i just checked and the time is correct.

**Comment by pvizeli** [comment]
Yeah, I think the issue is still happening on the docker server in your region (https://hub.docker.com/). We need still to wait until they fix the issue there. But they show also no error over https://status.docker.com/ which is weird because you log said there is a timeout between you and the docker system.

**Comment by ibBogdan** [comment]
So this is a bit weird:
this is what i have in developer tools
![image](https://user-images.githubusercontent.com/12171894/77889922-f0ca9a00-726e-11ea-808c-139e1599ae2a.png)

and this is what i have in logs

![image](https://user-images.githubusercontent.com/12171894/77889983-0344d380-726f-11ea-8925-607c5e873412.png)


Also the log file changed to 
Can't create container from hassio_dns: 404 Client Error: Not Found ("No such image: homeassistant/aarch64-hassio-dns:3")
from 
20-03-30 06:36:16 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config

The time seems to be 3 hours behind on logs

**Comment by ibBogdan** [comment]
logs in home-assistant.log are ok 
![image](https://user-images.githubusercontent.com/12171894/77890903-d7c6e680-7278-11ea-8517-da945220bd83.png)
date on the system is ok
![image](https://user-images.githubusercontent.com/12171894/77890936-e3b2a880-7278-11ea-8951-93e927bd22dd.png)


only those logs look weird

**Comment by pvizeli** [comment]
@ibBogdan 

```bash
ha dns update --version 2
ha dns update --version 3
```

What said the supervisor logs after that?

**Comment by aleksandrov1995** [comment]
I finally managed to update it, first to V2 then to V3. Seems to be stable for now, will keep you posted.

**Comment by ibBogdan** [comment]
seems to be working now. will keep you posted :D
thanks you

**Comment by dmvieira** [comment]
I need this one to work:

```
ha dns reset
```
