### ISSUE TITLE
Can't add custom repository

### ISSUE THREAD

**Issue by AkshatShah1** [home-assistant/supervisor#1727]
**Home Assistant release with the issue:**
-->Home Assistant 0.109.6

**Operating environment (HassOS/Generic):**
HassOS running on a Raspberry Pi 3 B+, nothing special at all

**Supervisor logs:**
-->

20-05-15 22:20:13 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/JoshuaMulliken/ha-wyzebulb repository

20-05-15 22:20:15 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/87977a50/repository.json: [Errno 2] No such file or directory: '/data/addons/git/87977a50/repository.json'

20-05-15 22:20:15 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/87977a50/repository.json

**Description of problem:**

I can't add a custom repository to my Home Assistant. I posted this issue in the repo's github where I was redirected to the HACS github where I was told this was a supervisor problem. I am new to using Home Assistant and this is the first time I've used GitHub so if I am doing something stupid or overlooking something simple, I apologize.

**Comment by frenck** [comment]
I'm sorry, @AkshatShah1, I don't want to send you from one place to the other, but you are in the wrong place...

So let me try to explain a bit about the ecosystem you seem to be struggling with a bit.

First add-ons: Add-ons are additional services/applications that can be run alongside Home Assistant. Think of things like Node-RED, a database server, an MQTT broker.

Integrations: Integrations live inside the Home Assistant core itself and allow Home Assistant to connect to other services or devices and "integrate" with them.

So essentially, running an add-on provides a service, while integration allows the Home Assistant Core to hook up to such service or device.

Add-ons and integrations are thus two totally different things. Home Assistant has around 1000 integration built-in, additional ones are often provided by HACS. Add-ons are installable via the Supervisor panel -> Add-on store.

Both the add-on store and HACS offer the possibility to add additional repositories that provide additional add-ons or integrations.

When looking at the link you have provide:

![image](https://user-images.githubusercontent.com/195327/82299043-4b51be00-99b5-11ea-8a72-a285f5807b0b.png)

☝️ It says "integration". Even more important, it provides a `hacs.json` file:

![image](https://user-images.githubusercontent.com/195327/82299103-63294200-99b5-11ea-8c31-0a758834b465.png)

This is a repository that should be added via HACS.

In this issue you have tried to add it to the Home Assistant Supervisor Add-on store, however, as concluded earlier, this is not an add-on, so that won't work.

Hoping this helps a bit! If you have further questions, I can highly recommend joining the Home Assistant Discord chat server.

../Frenck
