### ISSUE TITLE
Error parsing docker version

### ISSUE THREAD

**Issue by Blizzke** [home-assistant/supervisor#1815]
**Home Assistant release with the issue:**
Supervisor build 228 (227 had it as well)

**Supervisor logs:**
CRITICAL (MainThread) [supervisor.core] Docker version 19.03.10-ce is not supported by Supervisor!

**Description of problem:**
It seems that `supervisor/blob/dev/supervisor/docker/__init__.py` (line 45) parses my local version from `19.03.10-ce`, which returns a `LegacyVersion` instead of a regular one, causing the comparison to return `False`. Perhaps best to add a `replace "-ce", ""`?

**Comment by pvizeli** [comment]
Do you run a supported system?
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions

**Comment by Blizzke** [comment]
Not to be annoying, but what does that matter? 
I've been running HA for almost 2 years now without a single issue. 
This problem started when the supervisor updated to 227

**Comment by pvizeli** [comment]
Yes, and it means it stops working in a future release. So you can fix based on https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md

**Comment by spurgelaurels** [comment]
Correct me if I'm wrong here, but I understood the purpose of Home Assistant as an open source home automation tool to break free of proprietary ecosystems and grant the end user the options and abilities to build their system from scratch in any way they saw fit. 

We're talking about Arch Linux as an underlying host system here, and I can almost guarantee that anyone running the HASS Supervisor on Arch Linux will understand their system well enough to fix any issues themselves. Adding a breaking change to a version check based on a string mismatch and not an actual software interop issue does not seem to align with this purpose. 

Perhaps instead of simply closing tickets, it would be better to find a way to allow more advanced users to passlist certain version strings, or even version numbers themselves (useful for testing, downgrading, etc).

**Comment by pvizeli** [comment]
You have the full control over the cli to enable or disable functionality
