### ISSUE TITLE
Errors due to unchecked object access in Interface.from_dbus_interface in certain network configurations

### ISSUE THREAD

**Issue by sbyx** [home-assistant/supervisor#2338]
### Describe the issue

There are unchecked accesses to members of inet.settings.ipv4 and inet.settings.ipv6 here:
https://github.com/home-assistant/supervisor/blob/6245b6d82315a4961705dc97e935e01d95cca727/supervisor/host/network.py#L281
https://github.com/home-assistant/supervisor/blob/6245b6d82315a4961705dc97e935e01d95cca727/supervisor/host/network.py#L289

which causes supervisor to error in case of NetworkManager connections without the relevant ipv4 / ipv6 settings missing.
Adding a simple guard to check whether inet.settings.ipv4 or inet.settings.ipv6 exist should be sufficient.

### Steps to reproduce

1. Configure a network connection in NM with empty ipv4 / ipv6 settings, e.g. a bridge member.

### Enviroment details

- **Operating System:**: Ubuntu 20.04.1 LTS
- **Supervisor version:**: 2020.12.2
- **Home Assistant version**: 0.118.4

### Supervisor logs

    File "/usr/src/supervisor/supervisor/host/network.py", line 281, in from_dbus_interface
        Interface._map_nm_method(inet.settings.ipv4.method),
    AttributeError: 'NoneType' object has no attribute 'method'

**Comment by pvizeli** [comment]
> bridge member

We do currently not support bridge settings. But it should filter that out, modify your NetworkManager.conf to not manage bridge devices until we have the support for it (could take some years maybe). If a bit special because we filter unsupported kind fo device at: https://github.com/home-assistant/supervisor/blob/main/supervisor/dbus/network/__init__.py#L156

However, I don't have time to look at this and I have also no system. Please setup NM like we recommend: https://github.com/home-assistant/home-assistant.io/blob/current/source/more-info/unsupported/network_manager.markdown

I close this issue now because it is an unsupported system.
