### ISSUE TITLE
Fresh installation failed with: no supervisor internet connection

### ISSUE THREAD

**Issue by lawa42** [home-assistant/supervisor#2389]
I fail to install home-assistante 5.9 32 or 64 bit version on a raspberry pi4. I've tried different memory cards (one of them brand new). The installation always fails with

20-12-29 11:36:58 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
20-12-29 11:36:58 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec

There is an earlier WARNING:

WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Cannot connect to host version.home-assistant.io:443 ssl:default [Try again]

However, I can reach the starting page and also from the ha cli I have internet access

Let me know which other information I can provide

**Comment by 01706** [comment]
![no internet](https://user-images.githubusercontent.com/11318980/106659464-adc80a00-6596-11eb-8afc-fc430423ca97.png)
Having the same issue using 'hassos_ova-5.10.vdi' within virtual box. 

Home Assistant is getting a DHCP address (192.168.0.7) with DNS (router 192.168.0.1) but it wont install due to supervisor not having internet access. Pinging google.com from the CLI works so DNS is being resolved

**Comment by tokyotexture** [comment]
Same thing here on virtual box..

**Comment by ludeeus** [comment]
run `ha su restart`

**Comment by 01706** [comment]
Since my first comment I've played around with my setup and found the issue was the WireGuard server running on the host machine (Ubuntu 20.04), as soon as the WireGuard interface was stopped (wg-quick down wg0) the supervisor/home assistant running within VirtualBox was able to access the internet.

So it appears the virtual machine was having issues with WireGuard running on the host on the same interface as the bridged network. 

My solution was setup a USB passthrough with a USB Wi-Fi adapter on the VM and disable the bridged network with the host, effectively separating the two networks (host and VM).
![setup](https://user-images.githubusercontent.com/11318980/107147118-38688a80-6944-11eb-954b-deb4e0adde95.png)
It's not a conventional setup but it now works for me. Didn't have time to work out why WireGuard was cursing a issue with the supervisor, I just needed a working setup fast which could send notifications based on installed sensors.

**Comment by JonasArnold** [comment]
I have the same issue.
HomeAssistant OS is installed on a VM inside proxmox. No WireGuard installed as far as I know.
Has anybody already found a way to resolve this? Does a Re-install of HomeAssistant work?

**Comment by mhogberg2** [comment]
Same issue here!

**Comment by TheEngineerGuy** [comment]
Same here. Tried it on Debian 10 and Raspbian buster. 

```
WARNING (MainThread) [supervisor.plugins.dns] Error on install CoreDNS plugin. Retry in 30sec
WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
```

**Comment by lor26** [comment]
the same thing happened to me

reference:
https://tech.borpin.co.uk/2018/10/18/using-nmcli-to-set-a-static-ipv4-address-in-hass-io/

Login as root (no password needed)

At the hassio > prompt, type login (as instructed).

From here you will use the nmcli configuration tool.

# nmcli connection show will list the “HassOS default” connection in use.

# nmcli con edit “HassOS default” will put you in a position to edit the connection.

nmcli> print ipv4 will show you the ipv4 properties of this connection.

To add your static IP address (select ‘yes’ for manual method);

nmcli> set ipv4.addresses 192.168.100.10/24
Do you also want to set 'ipv4.method' to 'manual'? [yes]:
nmcli> save
nmcli> exit

nmcli> set ipv4.dns 192.168.100.1
nmcli> set ipv4.gateway 192.168.100.1
nmcli> save
nmcli> exit

keep in mind that the  ipv4.dns 192.168.100.1 and ipv4.gateway 192.168.100.1

both have to be the output of your router, in my case it is 192.168.1.1

**Comment by TheEngineerGuy** [comment]
I should have updated the thread. Yes that is what I had to do. For some reason RPi L3 interfaces are inaccessible to HASSIO container. 

I am container n00b, so I wonder if there is a way to enable a container to access local RPi L3 interfaces.

**Comment by fwidfeldt** [comment]
This problem has prevented me from migrating to HomeAssistant OS for quite some time. 
Now I finally realised that the underlaying problem was that the docker network that is created during setup have ip conflict with my local network. I run my local network on 172.17.0.x  which was exactly the same as the docker network was configured to. 
I fixed the problem by changing the docker network to 10.0.0.0 by following the guide here: https://community.home-assistant.io/t/change-docker0-network-from-172-16-0-0-16-due-to-ip-conflict/197634/5
