### ISSUE TITLE
After Reboot - no supervisor internet connection

### ISSUE THREAD

**Issue by kreisklasse** [home-assistant/supervisor#2695]
### Describe the issue you are experiencing

I had to shutdown the Host (odroid N2) and reboot it.
After that, recurring "warnings" with 
[supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
and errors (see below)
Restating of Host and Supervisor does not help, errors/warnings still come back.
So no updates to newer Supervisor or HA-Core are possible.

### What is the used version of the Supervisor?

supervisor-2021.02.11

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.2.3

### Steps to reproduce the issue

1. Rebooting Host - Warning/erros reoccur
2. Restart Supervisor - Warning/erros reoccur

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line
21-03-07 05:13:25 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
21-03-07 05:43:23 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-03-07 05:47:06 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-07 05:47:10 INFO (MainThread) [supervisor.host.services] Updating service information
21-03-07 05:47:10 INFO (MainThread) [supervisor.host.network] Updating local network information
21-03-07 05:47:13 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-03-07 05:47:13 INFO (MainThread) [supervisor.host] Host information reload completed
21-03-07 06:13:20 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-07 06:13:20 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-07 07:13:20 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-07 07:13:20 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-07 07:13:25 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
21-03-07 07:13:26 WARNING (MainThread) [supervisor.jobs] 'GitRepo.pull' blocked from execution, no supervisor internet connection
21-03-07 07:13:26 WARNING (MainThread) [supervisor.jobs] 'GitRepo.pull' blocked from execution, no supervisor internet connection
21-03-07 07:13:26 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-23932' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:101> exception=StoreJobError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 105, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 57, in wrapper
    raise self.on_condition()
supervisor.exceptions.StoreJobError
21-03-07 07:13:26 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-23931' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:101> exception=StoreJobError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 105, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 57, in wrapper
    raise self.on_condition()
supervisor.exceptions.StoreJobError
21-03-07 07:13:26 WARNING (MainThread) [supervisor.jobs] 'StoreManager.update_repositories' blocked from execution, no supervisor internet connection
21-03-07 07:13:26 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
```

## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 19.03.13
disk_total | 28.5 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | chrony (2.0.0), deCONZ (6.7.2), File editor (5.2.0), ZeroTier One (0.10.3), WireGuard (0.5.0), AdGuard Home (3.0.0), Grocy (0.11.0), Mosquitto broker (5.1.1), Node-RED (8.1.2), Z-Wave JS to MQTT (0.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

**Comment by kreisklasse** [comment]
additional info:
- switching off all Add-Ons and restarting Host/Supervisor did not fix problem
- Home-assistant is running on an SD-Card on odroidN2

**Comment by bakboord4** [comment]
Some additional info.

Same problem described as above.
But also under core-2021.3.0;  see below

Question: is HA recovering from this error possible outside complete rebuild with an applicable snapshot?
At this moment:
No snapshot recovering possible. 
And  I am afraid that given the current state of my HA, updates thru standard are not possible nor update available signals in HA.

----------------------------
## System Health

version | core-2021.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.4
docker_version | 19.03.13
disk_total | 228.5 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | failed to load: unreachable
installed_addons | Samba share (9.3.1), File editor (5.2.0), Check Home Assistant configuration (3.6.0), Mosquitto broker (5.1.1), ESPHome (1.16.2), Samba Backup (4.4), Z-Wave JS to MQTT (0.6.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 5
views | 7
mode | storage

</details>

**Comment by tombombolov** [comment]
Hi All, 
I am having a very similar issue to bakboord4 which started <24 hours ago for an unknown reason.
It seems that supervisor can't reach the internet after multiple restart attempts.
All my attempts to update software / core are not working because of this.

Log files look something like this.
21-03-08 01:49:16 INFO (MainThread) [supervisor.core] Supervisor reboot detected
21-03-08 01:49:16 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-03-08 01:49:16 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-03-08 01:49:16 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-08 01:49:16 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
21-03-08 01:49:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-08 01:49:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-08 01:49:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-08 01:49:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-08 01:49:16 WARNING (MainThread) [supervisor.jobs] 'CheckAddonPwned.run_check' blocked from execution, no supervisor internet connection

21-03-08 01:55:52 INFO (MainThread) [supervisor.hassos] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/5.12/hassos_rpi4-64-5.12.raucb
21-03-08 01:55:57 WARNING (MainThread) [supervisor.hassos] Can't fetch versions from https://github.com/home-assistant/operating-system/releases/download/5.12/hassos_rpi4-64-5.12.raucb: Cannot connect to host github.com:443 ssl:default [Try again]
21-03-08 01:56:01 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached
21-03-08 01:56:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-08 01:56:08 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-08 01:56:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-08 01:56:46 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reach

I hope I haven't hijacked this thread for an unrelated problem.

**Comment by pvizeli** [comment]
Maybe an application firewall that blocks access to the internet

**Comment by bakboord4** [comment]
@pvizeli , you may be right. Rebuild my test HA-RPi without ADGuard Home from the HA Add-on Store. Since a few days my test system is running oké without internet blocks. My assumption was that ADGuard is an official add-on that should be running out-of-the-box without causing problems. But, maybe the rebuild solved the problem.
@kreisklasse, still experiencing the same problem?

**Comment by kreisklasse** [comment]
I think today i found the problem. To make it short, it was not Home-Assistant (Core/Supervisor/OS), it was the FritzBox.

I saw that one program (Syncthing) on a other computer could not connext to all discovery-server on the  internet.
Then i thought about what @pvizeli wrote and what lies between HA, my other computer and the internet.
There's only my Router, a FritzBox, where the HA-odroid was directly plugged to a port.
So i restarted the Router, and immediatly HA received all updates.
Strange behavior of the FritzBox, because before restarting it, i could access the internet, beside HA and Syncthing, without restrictions.

From my side you can close this issue here. Thank you for your support.

**Comment by bakboord4** [comment]
@kreisklasse, thank you for your reaction. I also have a Fritz!Box as modem/router in my network. I will look in that direction as a possible cause of this HA connection problem. Also for me this issue can be closed. 
@kreisklasse are you not the owner/starter of this issue to close?

**Comment by kreisklasse** [comment]
> 
> 
> @kreisklasse are you not the owner/starter of this issue to close?

i am not that familiar with github, but will try ;-)
