### ISSUE TITLE
Ingress proxy unpacks assest and work slowly

### ISSUE THREAD

**Issue by nurikk** [home-assistant/supervisor#3339]
### Describe the issue you are experiencing

Hello from zigbee2mqtt team!

Recently many users started complaining that z2m frontend open slowly.

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/236
https://github.com/nurikk/zigbee2mqtt-frontend/issues/1124

After some debugging i can see that when frontend is loaded through ingress proxy, it's loaded very slowly:
there are few symptoms:
 - Assets aren't gzip compressed
 - Missing caching headers
 - Sometimes response comes in form of headers from underlying backend as is, kind of http response parsing issue
 
<img width="524" alt="Screenshot 2021-12-04 at 7 30 59 PM" src="https://user-images.githubusercontent.com/1525421/144707934-19f7d8dc-fc92-48c5-92b5-0ba158b32747.png">

Here're some screenshots

<img width="1440" alt="Screenshot 2021-12-03 at 10 31 18 AM" src="https://user-images.githubusercontent.com/1525421/144567914-cf39d012-634b-4103-85a0-1b5abd72d8d7.png">

<img width="382" alt="Screenshot 2021-12-03 at 4 51 00 PM" src="https://user-images.githubusercontent.com/1525421/144573582-040a432e-077b-45f3-842e-5015816c13c1.png">

This how it looks if we request frontend directly, without ingress
First load (no cache)

<img width="1440" alt="Screenshot 2021-12-03 at 10 26 37 AM" src="https://user-images.githubusercontent.com/1525421/144572218-e85741c4-2268-4416-8d86-560b032526dd.png">
<img width="388" alt="Screenshot 2021-12-03 at 10 27 48 AM" src="https://user-images.githubusercontent.com/1525421/144572280-2492bda3-fcf0-4fff-a588-ffb73d01f14e.png">

After refresh
<img width="1440" alt="Screenshot 2021-12-03 at 10 25 09 AM" src="https://user-images.githubusercontent.com/1525421/144572313-dcfbb301-6ad8-4570-85e8-8a21a7c8cf40.png">

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Ubuntu 18.04.6 LTS

### What version of Home Assistant Core is installed?

core-2021.11.5

### Steps to reproduce the issue

1. Install zigbee2mqtt addon
2. Start it
3. Open web ui

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Additional information
[nurikodd.duckdns.org.har.zip](https://github.com/home-assistant/supervisor/files/7653833/nurikodd.duckdns.org.har.zip)

Attached HAR archive from chrome dev tools

**Comment by nurikk** [comment]
Current workaround is to use websocat exported port for frontend and access directly on websocat port

<img width="582" alt="Screenshot 2021-12-02 at 7 44 38 PM" src="https://user-images.githubusercontent.com/1525421/144633736-53a98a6a-eab4-4575-8e67-60160f3f037e.png">

**Comment by nurikk** [comment]
Hey guys, may be you can help? @danielwelch @ciotlosm

**Comment by Bascht74** [comment]
right now the Z2M frontend looks like this every second time. If you press reload, everything is fine...
![image](https://user-images.githubusercontent.com/66269310/145593672-414d1b59-53a1-49dd-92fa-63dcc5ee8775.png)

![image](https://user-images.githubusercontent.com/66269310/145593918-854b748d-bed6-4787-8ebc-bb66ff68511f.png)

**Comment by Bascht74** [comment]
@frenck Hi, I am sorry that I "quoted" you directly in that issue, but I saw in the last HA shows that you use Z2M yourself. There is an issue with the frontend and ingress (which seems to be a part of HA supervisor). Maybe you face the problem yourself (you need to reload the frontend sometimes that it shows correctly)
@nurikk made this issue about it but no one seems to pick it up. Do you have any hint how to proceed? 
I saw problems with ingress when HA started using it but now I am not sure if there is somebody who will cover the ingress part...

**Comment by frenck** [comment]
@Bascht74 i don't use z2m as an add-on.

**Comment by Enzokot** [comment]
Keep alive

**Comment by Bascht74** [comment]
Bump

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by Bascht74** [comment]
bump. 

@danielwelch @ciotlosm can you take a look?

**Comment by Bascht74** [comment]
Anybody out here?

**Comment by Bascht74** [comment]
Still no reaction and no assignment. Is that right?

**Comment by mdegat01** [comment]
Hey sorry for the delay on this one @Bascht74 . I'm digging into this now. 

So first thing I noticed is that the `cache-control` header seems to be the same for both ingress and non-ingress connections to Z2M. And in my testing just now I do actually see Z2M hitting the cache when using ingress after the first refresh. I realize that its been a while since this bug was first reported, do  you see that change as well? Or are you still seeing Z2M skipping the cache?

Dev tools for Z2M direct access on second refresh with cache allowed:
![Screen Shot 2023-01-12 at 3 37 16 PM](https://user-images.githubusercontent.com/2037026/212175980-d8f703c6-f98e-4f5c-a71c-4f9fbaeb61bc.png)

Dev tools for Z2M ingress access on second refresh with cache allowed:
![Screen Shot 2023-01-12 at 3 38 48 PM](https://user-images.githubusercontent.com/2037026/212176115-981ebf90-5fac-4abb-9771-5690bee0373b.png)

Now for the other two parts. The response actually gets unpacked twice along the way to the client unfortunately. Since ingress everything from the HA frontend (including ingress requests) go to core first. Core then sees it is an ingress request and so passes it to supervisor. Supervisor then checks that it has a valid ingress session and if so passes it on to the addon. The process then runs in reverse for the response.

The request handling makes sense but the response handling is a bit illogical. Core obviously has to process the response since it is often asked to be the TLS endpoint by users when they add their SSL certs to its HTTP config. But supervisor never has to handle SSL and is basically just pass through. When I asked about this it seems there's a limitation in aiohttp around this. We let aiohttp handle encoding and apparently it always decodes response, there is no way to pass a response straight through without decoding it. I can research that more as that seems like the obvious improvement, perhaps something has changed.

Since supervisor currently has to decode the response it is currently leveraging that to decide whether to stream it in chunks or not:
https://github.com/home-assistant/supervisor/blob/0991f52100b49b3e5abd33d095ef38a915630d2d/supervisor/api/ingress.py#L189-L219
I'm suspicious that this is the source of your 0B responses but I'm having a hard time reproducing that. Do you still see that behavior?

The thing that seems like the top priority here is why isn't the response gzipped? I definitely see exactly what you're talking about there. My understanding is that this should be handled by aiohttp. The request headers include the accepted encodings so it should be encoding the output in one of the accepted formats. That doesn't seem to be happening which is confusing, will look into why.
