### ISSUE TITLE
Backup issues after upgrade to 2022.2.x

### ISSUE THREAD

**Issue by vicfalls** [home-assistant/supervisor#3432]
### The problem

since the update to 2022.2.x version, backup is not working anymore.
Here are my logs:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 13:17:10 (1 occurrences)
Last logged: 13:17:10

Failed to to call /backups/new/full - Unknown error, see supervisor

BTW, the automation does not work either....

Any idea?
Thanks
Vic

### What version of Home Assistant Core has the issue?

Home Assistant 2022.2.2

### What type of installation are you running?

Home Assistant OS

**Comment by vicfalls** [comment]
Hi Joakim, I still have the issue doing a backup. System health and log....

## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Vienna

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4945
Installed Version | 1.22.0
Stage | running
Available Repositories | 1044
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 28.6 GB
disk_used | 11.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), AppDaemon 4 (0.8.1), Terminal & SSH (9.3.0), Node-RED (11.0.1), Grafana (7.4.1), InfluxDB (4.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 5
views | 19
mode | storage

</details>

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 21:56:12 (1 occurrences) 
Last logged: 21:56:12

Failed to to call /backups/new/full - Unknown error, see supervisor


22-02-14 21:56:12 ERROR (MainThread) [supervisor.backups.manager] Backup 87266d3f error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 149, in _do_backup
    await backup.store_homeassistant_config_dir()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 486, in store_homeassistant_config_dir
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 330, in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 321, in _write_tarfile
    atomic_contents_add(
  File "/usr/src/supervisor/supervisor/utils/tar.py", line 180, in atomic_contents_add
    tar_file.add(directory_item.as_posix(), arcname=arcpath, recursive=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1979, in add
    self.addfile(tarinfo, f)
  File "/usr/local/lib/python3.9/tarfile.py", line 2007, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
OSError: [Errno 5] I/O error

**Comment by agners** [comment]
It seems that a file is not readable. Is the host log showing something?

**Comment by Hoppersusa** [comment]
I had the same issue rolled back to the pre Jan 5th changes made to backup.py and manager.py and the problem is resolved. The value of backup.store_homeassistant_config_dir() appears to be undefined in the newer version of these files.

**Comment by vicfalls** [comment]
thanks for the feedback
@agners I went back to a late January version, my log doesn't show any suspicious issue.
@Hoppersusa, can you give me some more information? How can I go back to backup.py and manager.py files (pre Jan 5th) and where do I need to copy them at HASS? 
Thanks

**Comment by Hoppersusa** [comment]
Sir, if you connect to the hassio_supervisor container with ‘docker exec -it hassio_supervisor /bin/bash’, then go to /usr/src/supervisor/supervisor/backups/ within that container. Replace the existing backup.py and manager.py with the version prior the Jan 5th change then you should be able to backup like you were previously.

I just renamed the existing files and created new ones and pasted the code from Github for those files from commit https://github.com/home-assistant/supervisor/commit/d8c934365aa0777c9609543f54ec76f18df1f204 This is a short term fix when there is a supervisor update this will be lost but I hoping the next update fixes this issue anyway. ☺

Hope that is of some help, let me know if that does not work for you.

Cheers,
Hoppers

**Comment by agners** [comment]
@Hoppersusa did you had the same stack trace as @vicfalls is repoting?

I am not quite sure what you meant with "The value of backup.store_homeassistant_config_dir() appears to be undefined". That is a function...

Meanwhile more changes in the backup area got added to dev. What would be good if you can test the current dev version of Supervisor, and see if it fixes it:

```
ha su options --channel=dev
ha su reload
ha su update
```

Also set it back to stable afterwards:
```
ha su options --channel=stable
ha su reload
```

**Comment by Hoppersusa** [comment]
@agners I did not have exactly the same stack unfortunately. I have updated to the dev version and unfortunately the backup does not complete. Trace Below for reference.

The difference seems to be the same I/O error in the earlier code did not abort the back up. It just skipped that directory (in this case a cloud drive mount) and continued on which is why I had not noticed the issue until the Jan update. I see the files being built out in the tmp directory and then clear but no tar file in the backup directory as I assume the error causes the in progress backup to be purged.  Is there a way I can exclude that one directory from the backup?

22-02-28 01:03:05 ERROR (MainThread) [supervisor.jobs] Unhandled exception: [Errno 5] I/O error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 352, in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 343, in _write_tarfile
    atomic_contents_add(
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 179, in atomic_contents_add
    tar_file.add(directory_item.as_posix(), arcname=arcpath, recursive=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1979, in add
    self.addfile(tarinfo, f)
  File "/usr/local/lib/python3.9/tarfile.py", line 2007, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
OSError: [Errno 5] I/O error
22-02-28 01:03:05 ERROR (MainThread) [supervisor.backups.manager] Backup f16504b6 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 352, in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 343, in _write_tarfile
    atomic_contents_add(
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 176, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 179, in atomic_contents_add
    tar_file.add(directory_item.as_posix(), arcname=arcpath, recursive=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1979, in add
    self.addfile(tarinfo, f)
  File "/usr/local/lib/python3.9/tarfile.py", line 2007, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
OSError: [Errno 5] I/O error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 150, in _do_backup
    await backup.store_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 466, in store_homeassistant
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 112, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException

**Comment by agners** [comment]
> The difference seems to be the same I/O error in the earlier code did not abort the back up. It just skipped that directory (in this case a cloud drive mount) and continued on which is why I had not noticed the issue until the Jan update.

Hm, yeah I see, it should have printed a warning though. So the current code aborts now when a file in the config folder is not readable. We probably should continue, as before. That said, it means that you won't have a backup of the Core config folder! You should try to find what is wrong exactly.

You can use the following command to try to read every file in the config folder:

```
find /mnt/data/supervisor/homeassistant/ -type f -exec echo {} \; -exec grep -e SOMESTR {} \;
```

**Comment by Hoppersusa** [comment]
@agners Thank you sir that directory is huge but reads fine it is a VFS (rclone mount) which maybe why it causes errors. I would prefer to exclude it as it would add 100's of Gb to the back up. Is there an easy way to get back to the stable version of the supervisor with the dev version my system is not coming up after a restart. I had hoped I could just do: ha su update --version=2022.01.1 but I get
Error: No supervisor update available - 2022.02.dev2402

**Comment by pvizeli** [comment]
This setup is not supported

**Comment by agners** [comment]
@Hoppersusa just do a partial backup and exclude Home Assistant Core from backup then.

**Comment by vicfalls** [comment]
gents, I was not successful in any event....
here is the supervisor log

> 22-02-28 17:38:18 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_full' blocked from execution, system is not running - CoreState.FREEZE 
22-02-28 17:38:49 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files
22-02-28 17:38:49 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files
22-02-28 17:39:08 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - CoreState.FREEZE
22-02-28 17:39:15 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - CoreState.FREEZE
22-02-28 17:40:26 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_full' blocked from execution, system is not running - CoreState.FREEZE
22-02-28 17:41:16 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files
22-02-28 17:41:16 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files
22-02-28 17:46:19 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-28 17:48:13 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files
22-02-28 17:48:13 INFO (MainThread) [supervisor.backups.manager] Found 2 backup `files

don't know what to do.
Thanks for your support

**Comment by jamesking210** [comment]
I'm having the same issues

22-03-02 20:55:05 ERROR (MainThread) [supervisor.backups.manager] Backup 7090cbf9 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 149, in _do_backup
    await backup.store_homeassistant_config_dir()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 486, in store_homeassistant_config_dir
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 330, in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 321, in _write_tarfile
    atomic_contents_add(
  File "/usr/src/supervisor/supervisor/utils/tar.py", line 180, in atomic_contents_add
    tar_file.add(directory_item.as_posix(), arcname=arcpath, recursive=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1979, in add
    self.addfile(tarinfo, f)
  File "/usr/local/lib/python3.9/tarfile.py", line 2007, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
OSError: [Errno 5] I/O error

have had this issue since 22.2
Version core-2022.3.0 
Version supervisor-2022.01.1 
Channel stable 

40% used space on VM drive

Looks like it hasn't done a full backup since 1.30.22 (22.1)

**Comment by agners** [comment]
@vicfalls @jamesking210 do you use `rclone` or another manual mount as your config folder? If so, that is not a use case we currently support.

@jamesking210 are you using HAOS?

**Comment by jamesking210** [comment]
@agners i am only using HAOS running through an Oracle VM on a ubuntu 18.04 host machine. nothing manually mounted on the host, no rclone. i do have the google cloud backup add on in HA installed either way can not run full backups. when i back up partial/add-ons it works but the folders or the system, it throws that error above. I will try and removing google backup to see if thats the hangup

**Comment by vicfalls** [comment]
> @agners i am only using HAOS running through an Oracle VM on a ubuntu 18.04 host machine. nothing manually mounted on the host, no rclone. i do have the google cloud backup add on in HA installed either way can not run full backups. when i back up partial/add-ons it works but the folders or the system, it throws that error above. I will try and removing google backup to see if thats the hangup

same for me, I'm only using HASS

**Comment by jamesking210** [comment]
my issues are resolved as of today.
I had an update to core-2022.3.3 waiting for me) from 22.3.2 so i did it.
Log back in after a restart and it was on version 22.1.1 with an update  to 22.3.3 available - i thought it was an error so i restarted, still showed i was on 22.1.1 and tried backups and it worked.
I upgraded to core-2022.3.3 - Works like a charm. so not sure why it rolled me back but it worked so im not mad.
