### ISSUE TITLE
 Supervisor 22.03.2: Can't validate backup

### ISSUE THREAD

**Issue by JohnnyM84** [home-assistant/supervisor#3499]
### Describe the issue you are experiencing

After upgrade to Supervisor 22.03.2 error in log that backup's cannot be read.
I have it on my supervised system with debian 11 and on a raspberrypi with ha os.

after deleting backups error is away and i can make new backups.

### What is the used version of the Supervisor?

supervisor-2022.03.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 11 (bullseye)

### What version of Home Assistant Core is installed?

core-2022.2.9

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/9968f77e.tar: expected boolean for dictionary value @ data['protected']. Got '8'
```

**Comment by Enzokot** [comment]
Same with supervisor-2022.03.3

**Comment by mini1368** [comment]
Same problem here

**Comment by Dominic-070** [comment]
same problem

**Comment by mekaneck** [comment]
I had this same issue, and although @frenck commented the CodeNotary issue is not related I suspect it may be related to the cause.
> @JohnnyM84 That issue is not related to this reported issue. Please raise a separate issue for that. Thanks 👍
> 
> _Originally posted by @frenck in https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063789175_

While attempting to upgrade to supervisor-2022.03.2 I encountered the CodeNotary issue documented in that thread, and was unable to complete the upgrade. I tried the upgrade several times (prior to realizing that it was a widespread issue) and for each update I had the option to 'create a backup' enabled. After the CodeNotary issue was resolved, I then completed the supervisor upgrade successfully, and that is when I encountered the error from this issue (`expected boolean, got '8'`) on the backups which were created during the failed upgrade attempts. I then deleted those specific backups because I didn't need them, and the issues is obviously now gone. 

I'd be interested if the others who have this issue could comment if it is specifically related to backups which were created during a failed upgrade attempt during the CodeNotary issue.

**Comment by mvv588** [comment]
> I'd be interested if the others who have this issue could comment if it is specifically related to backups which were created during a failed upgrade attempt during the CodeNotary issue.

I was just now still stuck with the update not working, removing the backups seemingly resolved the issue, tnx.

**Comment by nickizgr8** [comment]
@mekaneck "I'd be interested if the others who have this issue could comment if it is specifically related to backups which were created during a failed upgrade attempt during the CodeNotary issue."  - This is my issue exactly. I've been trying to trouble shoot this for two days. I backed up home assistant on Tuesday 3/8/22 to migrate from one ssd to another. I downloaded the full backup to my pc and restored it to home assistant on the new ssd. None of my addons have loaded and have not been able to resolve. My logs from that day had multiple mentions of "codenotary" and google searching led me to that thread https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063789175. I've been following that thread since yesterday hoping for a resolution but none have worked. I've restarted home assistant several times so do not have the original log mentioning the error but my current logs look like this: 

` File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'core_almond'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on core_almond: 
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon 15ef4d2f_esphome
22-03-11 00:12:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: '15ef4d2f_esphome'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: '15ef4d2f_esphome'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on 15ef4d2f_esphome: 
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_configurator
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_configurator
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Finished restore for add-on core_configurator
22-03-11 00:12:23 WARNING (MainThread) [supervisor.ingress] Fails Ingress panel for core_configurator with 500
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_google_assistant
22-03-11 00:12:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'core_google_assistant'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'core_google_assistant'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on core_google_assistant: 
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_grafana
22-03-11 00:12:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_grafana'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'a0d7b954_grafana'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on a0d7b954_grafana: 
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_ada
22-03-11 00:12:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'core_ada'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'core_ada'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on core_ada: 
22-03-11 00:12:23 INFO (MainThread) [supervisor.addons.addon] Restore config for addon cebe7a76_hassio_google_drive_backup
22-03-11 00:12:23 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'cebe7a76_hassio_google_drive_backup'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'cebe7a76_hassio_google_drive_backup'
22-03-11 00:12:23 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on cebe7a76_hassio_google_drive_backup: `

**Comment by henriklund** [comment]
Running Home Assistant Operating System (core-2022.3.3 / supervisor-2022.03.3) I get a similar error for 19 out of 38 backups (the '19' does not change if I create new backup):
`[supervisor.backups.backup] Can't validate data for /data/backup/48efccca.tar: expected boolean for dictionary value @ data['protected']. Got '4'` 

Those 19 backups are visible in CLI, but not in Supervisor. Oddly enough, refreshing the Supervisor backup page adds blank lines to the page (sufficient to show 19 backups).

**Comment by peter-vanpoucke** [comment]
same issue on my setup

**Comment by chiboule** [comment]
I had same issue on rpi4. I can't restore backups that have been encrypted with password. I did a fresh install of home assistant 7.5 and blocked internet access before installation.  After some minutes,  i opened access to internet. The core has been updated to 22.3.3 but not the supervisor who remained under 22.03.2. From there i could restore my encrypted backup now all is running smoothly, after last updated supervisor.  I did new fresh backup from there, without password protection and is ok..

**Comment by dominicairportindoorparking** [comment]
> I had same issue on rpi4. I can't restore backups that have been encrypted with password. I did a fresh install of home assistant 7.5 and blocked internet access before installation. After some minutes, i opened access to internet. The core has been updated to 22.3.3 but not the supervisor who remained under 22.03.2. From there i could restore my encrypted backup now all is running smoothly, after last updated supervisor. I did new fresh backup from there, without password protection and is ok..

Dear Chiboule, Can you indicate when you reconnect the internet? I have tried several times. too early: then the supervisor will be updated. too late: then it gives an error with the CLI and the landing page is not loaded.

**Comment by Dominic-070** [comment]
> I had same issue on rpi4. I can't restore backups that have been encrypted with password. I did a fresh install of home assistant 7.5 and blocked internet access before installation. After some minutes, i opened access to internet. The core has been updated to 22.3.3 but not the supervisor who remained under 22.03.2. From there i could restore my encrypted backup now all is running smoothly, after last updated supervisor. I did new fresh backup from there, without password protection and is ok..

Dear Chiboule, Can you indicate when you reconnect the internet? I have tried several times. too early: then the supervisor will be updated. too late: then it gives an error with the CLI and the landing page is not loaded.

**Comment by chiboule** [comment]
> > I had same issue on rpi4. I can't restore backups that have been encrypted with password. I did a fresh install of home assistant 7.5 and blocked internet access before installation. After some minutes, i opened access to internet. The core has been updated to 22.3.3 but not the supervisor who remained under 22.03.2. From there i could restore my encrypted backup now all is running smoothly, after last updated supervisor. I did new fresh backup from there, without password protection and is ok..
> 
> Dear Chiboule, Can you indicate when you reconnect the internet? I have tried several times. too early: then the supervisor will be updated. too late: then it gives an error with the CLI and the landing page is not loaded.

I wait 5 minutes more or less, you can see logs when installing and the system try to access internet and say that it retry after 30s. Let this message appear +- 10 times and then, reconnect,  only core will be updated. You must use image version max 7.5 (mine was 7.5)

**Comment by Dominic-070** [comment]
I noticed that in the backup.tar file, in the file backup.json is a value protected: "8".

If you make a protected backup with the new supervisor 2022.03.3 or 4, it has the value protected: "true"

**Comment by chiboule** [comment]
> I noticed that in the backup.tar file, in the file backup.json is a value protected: "8".
> 
> If you make a protected backup with the new supervisor 2022.03.3 or 4, it has the value protected: "true"

When you disconnects from internet, you have to leave the rj45 câble plugged in and must block internet access from you routers's settings. You have to load your backup from first setting page (link in the bottom. from page) ,  when ha ask for name, user name.. .

**Comment by Do-AIP** [comment]
Thanks for your comment.
I tried but it hangs on restoring the backup. Despite the supervisor being older than 2022.3.x.
I'm afraid I'll have to wait for a fix.
