### ISSUE TITLE
Default Home Assistant OS installation doesn't get up and running without an internet connection

### ISSUE THREAD

**Issue by redgryphon** [home-assistant/supervisor#3513]
### Describe the issue you are experiencing

Easy bug to be described and reproduced, at least.

The issue is simple: without internet the first setup cannot be completed.

A total offline setup (apart for downloading the VM image) would be really useful for the parts of the world where internet is not always available yet one would like to have their home automated and managed. Obviously everything has to rely only on LAN services and not cloud ones. I imagine a cabin in the woods with some gardening stuff that can be automated but without an internet connection.

Following a deeper description of the problem and which are the components affected.

Following the docs for a VM installation I downloaded the vmdk file since I'm running VMware. I am pretty sure this happens with Virtualbox or KVM as well so no big deal with the installation media. I setup the VM as instructed and spun up in a limited environment (three VMs, one is a router-firewall distribution as pfSense or OPNsense and the other is a client machine with a browser).

If the virtual NIC on the WAN side of the firewall is connected then the Home Assistant OS installation works and arrives to the "create new user page" as showed in the first part of the [onboarding guide](https://www.home-assistant.io/getting-started/onboarding/). No big deal here.

If the virtual NIC is disconnected the entire installation hangs and doesn't show the first part of the initial wizard which is expected since the wizard is contained inside the Docker image that cannot be pulled from the internet.

The logs available in the ha supervisor logs command of the VM console keep raising [this exception](https://github.com/home-assistant/supervisor/blob/d2dc78ae6aa592a0687f8421266996bb239a9163/supervisor/jobs/decorator.py#L159).

I wonder if it would be possible to ship the image available at the time of creation of the VM disk and letting that deal with the initial setup.

### What is the used version of the Supervisor?

NOT AVAILABLE

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.4

### What version of Home Assistant Core is installed?

NOT AVAILABLE

### Steps to reproduce the issue

1. Create three VMs
- Firewall appliance like pfSense or OPNsense with two NICs
- Client VM to use the browser and test the configuration
- Home Assistant OS
2. Connect the firewall to the internet with the WAN NIC and to a LAN with the other
3. Connect the other two VMs to the LAN interface
4. Configure the firewall to NAT exactly as a home router would do
5. Power on the Home Assistant OS VM

### Anything in the Supervisor logs that might be useful for us?

```txt
Logs accessible from (ha supervisor logs) keep showing "[supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection".
```

### Additional information

![haos_no_internet](https://user-images.githubusercontent.com/74600987/158054722-f43a013e-f6f9-4640-9d9a-9d2bf938a424.png)

**Comment by redgryphon** [comment]
I forgot to mention that I would be happy to start contributing to a working solution but before writing code and submitting a PR I need some guidance on the matter from the community to understand the best approach to the solution.

**Comment by drthanwho** [comment]
This is expected of course right? All images of HAOS don't include HA Core in to ensure upon a fresh installation you get the latest possible HA Core (and Supervisor for that matter) rather than outdated versions. OS images aren't necesarrilly build that often so you'd quickly end up with outdated versions of Supervisor and Core. 

I don't think the developers would want to change this design.

The simplest solution would be to simply start the fresh installation at the point when you download the image and then take the installation offline. However, it should also be mentioned that the HAOS installation method is intended for being always online (or mostly). Offline HAOS installations will likely result in errros, especially without proper configurations for local NTP servers. For an offline installation you'd be better off with a HA container installation.

**Comment by redgryphon** [comment]
> This is expected of course right? All images of HAOS don't include HA Core in to ensure upon a fresh installation you get the latest possible HA Core (and Supervisor for that matter) rather than outdated versions. OS images aren't necesarrilly build that often so you'd quickly end up with outdated versions of Supervisor and Core.

If it is I really think it should not. A HAOS build should work out of the box even with an old build of the Supervisor and Core Docker image. And the Docker builds that should be provided inside the HAOS build should obviously be good enough for production use at the time the HAOS build is released.

If the HAOS build is shipped as stable, as it obviously is when it's out, then what would be the issue there?


> I don't think the developers would want to change this design.

If something isn't done today (for many reasons, maybe they just didn't have time to develop the code to solve this problem and they will be happy to get help) it doesn't mean it couldn't be done tomorrow.

> The simplest solution would be to simply start the fresh installation at the point when you download the image and then take the installation offline.

Which is exactly what shipping a build does. It gets built online and can be taken offline afterwards.

> However, it should also be mentioned that the HAOS installation method is intended for being always online (or mostly).

Online to what? To the LAN? Obviously! To the internet? If it doesn't rely on external services (and this depends on the needs of the user) not so much.

> Offline HAOS installations will likely result in errros, especially without proper configurations for local NTP servers.

This is because the software has a bug on that (see home-assistant/operating-system#689 ), not because it is designed that way.

> For an offline installation you'd be better off with a HA container installation.

Which needs the container either to be downloaded offline by the user, exactly what downloading the HAOS build is designed for, among the other things it does.

**Comment by mdegat01** [comment]
It's not one image actually, its a list of images. OS would need to include the current images for every supported component. Which means:
- Supervisor
- Core
- [All plugins](https://github.com/home-assistant?q=plugin-&type=all&language=&sort=)
- [OS Agent](https://github.com/home-assistant/os-agent) (not an image but also still needed)
- All apparmor profiles

Probably more, this is just off the top of my head. Also all of the images have an image per supported architecture. And some (like core) even have machine type specific images (like the image I'm running for core right now is `ghcr.io/home-assistant/odroid-n2-homeassistant` which is specifically for the odroid-n2 machine). So to do this we'd need to build quite an array of operating systems and trust the user to select the right one for their machine (since if they get it wrong we can't correct it without internet).

Also even then best case scenario is you have a system that runs but tells the user it is unsupported. Which is true because we are unable to do content-trust validations of all these images without an internet connection (need to be able to reach [CAS](https://cas.codenotary.com/) for that).

I'm going to close this because this is in the wrong place. This is really a feature request for HAOS to run completely offline so it should be [here](https://github.com/home-assistant/operating-system/discussions). I'm not saying it can't be done but I think its quite a bit of work. A lot of changes to the build process (after collecting a comprehensive list of all the things that would need to be included), new tests to ensure we don't miss new things being added which need to be offlined, and small feature requests to other components (like the CAS one) yet to be identified.

And in the end we'd have to figure out a way to make this actually approachable to users. Pointing users at a directory listing with a download button for every supported machine+arch combo and asking them to please choose wisely isn't really going to work
