### ISSUE TITLE
Incorrect password on snapshot restore fails quietly

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/supervisor#3514]
### Describe the issue you are experiencing

When restoring from a snapshot if the user inputs an incorrect password into the password box and clicks restore, the restore process begins and then spits out some opaque errors.

Ideally the UI would pop up an incorrect password error.

### What is the used version of the Supervisor?

supervisor-2022.03.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.4

### What version of Home Assistant Core is installed?

core-2022.3.3

### Steps to reproduce the issue

1. Create a password protected snapshot
2. Restore from it, partial or full - use an incorrect password
3. Watch as it tries to restore then spits out the above logs

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-13 11:16:48 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-03-13 11:16:48 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-03-13 11:16:56 INFO (MainThread) [supervisor.backups.manager] Full-Restore 1331b368 start
22-03-13 11:16:56 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' stopping 0 add-ons
22-03-13 11:16:56 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping homeassistant application
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' stopping 0 add-ons
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' stopping 0 add-ons
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' stopping 0 add-ons
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 Docker config
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 folders
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder share: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder addons/local: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder ssl: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder media: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 Home Assistant Core
22-03-13 11:17:50 ERROR (MainThread) [supervisor.homeassistant.module] Can't read tarfile <securetar.SecureTarFile object at 0x7f8e7889a0>: not a gzip file
22-03-13 11:17:50 ERROR (MainThread) [supervisor.backups.manager] Restore 1331b368 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 378, in restore
    await self.sys_run_in_executor(_extract_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 374, in _extract_tarfile
    with tar_file as backup:
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 82, in __enter__
    self._tar = tarfile.open(fileobj=self, mode=self._tar_mode, dereference=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1639, in open
    stream = _Stream(name, filemode, comptype, fileobj, bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 370, in __init__
    self._init_read_gz()
  File "/usr/local/lib/python3.9/tarfile.py", line 477, in _init_read_gz
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 252, in _do_restore
    task_hass = await backup.restore_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 480, in restore_homeassistant
    await self.sys_homeassistant.restore(homeassistant_file)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 380, in restore
    raise HomeAssistantError(
supervisor.exceptions.HomeAssistantError: Can't read tarfile <securetar.SecureTarFile object at 0x7f8e7889a0>: not a gzip file
22-03-13 11:17:50 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
22-03-13 11:17:51 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
```

**Comment by Do-AIP** [comment]
I am also having problems with backups since supervisor 2022.3.x .

The backup file contains a backup.json file. Even before supervisor 2022.3.x, the file contained " protected: '8' ".
now it expects the value true or false.

22-03-16 01:23:28 INFO (MainThread) [supervisor.backups.manager] Found 27 backup files
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/7bbdd9f0.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/5d78868e.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/70c3ed11.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/905f8b12.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/1ae252fd.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/209c8182.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/7d8d084c.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/acaa57ad.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/a4edb45b.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/a70050e7.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/15d97dac.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/79a98f6f.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/019649bb.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/1ce23b4a.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/4c718a32.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/260aeae7.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/4d95afbe.tar: expected boolean for dictionary value @ data['protected']. Got '8'
22-03-16 01:23:28 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/d2df375a.tar: expected boolean for dictionary value @ data['protected']. Got '8'
