### ISSUE TITLE
Supervisor Error Cant update github addons

### ISSUE THREAD

**Issue by robertboccia** [home-assistant/supervisor#3575]
### The problem

ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Reference at 'HEAD' does not exist.

### What version of Home Assistant Core has the issue?

2022.4.3

### What was the last working version of Home Assistant Core?

2022.4.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Supervisor

### Diagnostics information

ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Reference at 'HEAD' does not exist.

### Example YAML snippet

```yaml
ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Reference at 'HEAD' does not exist.
```

### Anything in the logs that might be useful for us?

```txt
22-04-14 08:42:16 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1459664' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 152, in pull
    branch = self.repo.active_branch.name
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 292, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'HEAD' does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by sdotter** [comment]
I have the same problem too

**Comment by ruleechen** [comment]
+1 keep seeing the same problem.

**Comment by stu1811** [comment]
Is this the same issue or different?

```
22-04-15 07:43:16 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: Could not read from remote repository.'.
22-04-15 07:43:16 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-801987' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: Could not read from remote repository.'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by mundeczek** [comment]
In my Supervisor 2022.04.0 logs same issue:
`22-04-15 15:11:24 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-4632977' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError`

**Comment by jum0n** [comment]
Also, this is still there after update to 2022.4.4

**Comment by Wingman3434** [comment]
I'm also getting the same error on 2022.4.4

22-04-15 23:40:07 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Reference at 'HEAD' does not exist.
22-04-15 23:40:07 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-10416' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 152, in pull
    branch = self.repo.active_branch.name
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 292, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'HEAD' does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError

**Comment by to4ko** [comment]
same here, right after 2022.4.4

<details>
<summary>details ...</summary>
`22-04-15 16:40:00 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'.
22-04-15 16:40:00 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / a0d7b954
22-04-15 16:40:00 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_RESET - ContextType.STORE / a0d7b954
22-04-15 16:40:00 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1108' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError`

</details>

**Comment by tngarner** [comment]
+1 same issue and same log lines as others

**Comment by Enzokot** [comment]
Same here with `supervisor-2022.04.0` and `core-2022.4.4`
<details><summary>Errors supervisor log</summary>
<code>
22-04-15 18:01:02 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'.
22-04-15 18:01:02 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: error reading section header 'acknowledgments''.
22-04-15 18:01:02 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / core
22-04-15 18:01:02 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_RESET - ContextType.STORE / core
22-04-15 18:01:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-197042' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: error reading section header 'acknowledgments''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
22-04-15 18:01:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-197045' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
</code>
</details>

**Comment by sharoltd** [comment]
Same with HA 2022.2.9

**Comment by mdegat01** [comment]
So I'm not going to resolve this one as a duplicate because the error you're seeing is slightly different and its about a different repository. But it looks very similar to #3561 even down to the git error code so I think it is a duplicate.

Which means for now my approach is the same as what I laid out [here](https://github.com/home-assistant/supervisor/issues/3561#issuecomment-1100098520). Basically a change was made in core `2022.4` which made it so supervisor is checking for updates in every addon repository every 5 minutes. This means that every 5 minutes every HA user with core >= `2022.4` and supervisor is cloning both the official add-ons repo and the community add-ons repo. My guess based on the error codes is that github does not like this activity and is blocking requests periodically to reduce load.

There is a [PR merged](https://github.com/home-assistant/core/pull/70075) already that changes it so core stops forcing supervisor to check for updates every 5 minutes and supervisor can resume checking on its schedule (every couple hours or so). That's slated for the next patch (`2022.4.5`). If the issue continues after that has been out for a day or two (giving most users time to update) then I will start to dig into it further. Because it doesn't really make sense otherwise, both of those repos definitely exist.

**Comment by tuxamat** [comment]
I have the same problem 
4.4

**Comment by mdegat01** [comment]
FYI 2022.4.5 out now with the mentioned fix for the hassio component

**Comment by mundeczek** [comment]
After update Core to 2022.4.5:
```
22-04-16 21:25:11 INFO (SyncWorker_1) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/qemux86-64-homeassistant:2022.4.4']
22-04-16 21:25:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-04-16 21:25:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-04-16 21:25:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-04-16 21:34:53 INFO (MainThread) [supervisor.resolution.fixups.store_execute_reset] Reset corrupt Store: a0d7b954
22-04-16 21:34:54 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/hassio-addons/repository repository
22-04-16 21:35:29 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
'.
22-04-16 21:35:29 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.FATAL_ERROR - ContextType.STORE / a0d7b954
22-04-16 21:35:29 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / a0d7b954
22-04-16 21:35:29 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: a0d7b954
22-04-16 21:35:29 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/hassio-addons/repository
22-04-16 21:35:29 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-04-16 21:45:00 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-04-16 21:45:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-04-16 21:45:17 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-04-16 21:45:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-04-16 21:45:30 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
```
Looks ok or something is wrong?

**Comment by mdegat01** [comment]
@mundeczek we're going to need to give it a few days. Most users are not on 2022.4.5 yet and so still hammering those repos. Not everyone updates immediately, can see the pattern here: https://analytics.home-assistant.io/

**Comment by ruleechen** [comment]
Great! 2022.4.5 works for me now.
I'm seeing anohter error while checking this issue:

22-04-18 09:35:57 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!

**Comment by tomlut** [comment]
Just came looking for that error. 
```
ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
```
Logged every hour. Running core-2022.4.5, supervisor-2022.04.2 (beta)
