### ISSUE TITLE
 I can no longer update my home assistant core 2022.4.1

### ISSUE THREAD

**Issue by hanskulker** [home-assistant/supervisor#3591]
### The problem

 I can no longer update my home assistant core. 
My last installed version is core-2022.4.1 and it still works fine. 
I can't install 4.2 and 4.3 and 4.4. 
My system is a NUC with Debian 11 and supervisor-2022.04.0
It is also no longer possible to perform apt update, this gives a temporary error when looking up deb.debian.org 
The log file keeps showing the following error: 
ERROR (MainThread) [supervisor.store.repository] Can't remove built -in repositories! 

I also tried a fresh install on my backup system. This is no longer possible . 
This gives no error messages until after the installation, but homeassistant cannot be started in the docker container.  
Also it is no longer possible to perform apt update this gives temporary error when looking up deb.debian.org

### What version of Home Assistant Core has the issue?

core-2022.4.2 and higher

### What was the last working version of Home Assistant Core?

core-2022.4.1

### What type of installation are you running?

Home Assistant Supervised

**Comment by tdejneka** [comment]
A bug that forces the user to re-install, what was previously a perfectly functional system, is a nasty bug.

**Comment by tdejneka** [comment]
**FYI**

Here's how I resolved this problem:

https://github.com/home-assistant/supervisor/issues/3582#issuecomment-1107517238

**Comment by hanskulker** [comment]
Unfortunately Unfortunately after a fresh install it seemed to work fine. Tried to update from 2022-4-6 to 7 this morning but again the error below.

22-04-25 11:48:07 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.4.7
22-04-25 11:48:07 INFO (SyncWorker_4) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2022.4.6 to ghcr.io/home-assistant/qemux86-64-homeassistant:2022.4.7
22-04-25 11:48:07 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2022.4.7.
22-04-25 11:48:23 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2022.4.7: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.4.7&fromImage=ghcr.io%2Fhome-assistant%2Fqemux86-64-homeassistant&platform=linux%2Famd64: Internal Server Error ("Head "https://ghcr.io/v2/home-assistant/qemux86-64-homeassistant/manifests/2022.4.7": Get "https://ghcr.io/token?scope=repository%3Ahome-assistant%2Fqemux86-64-homeassistant%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)")
22-04-25 11:48:23 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed.

Help Help

**Comment by hanskulker** [comment]
I was probably too early to update. Probably problems with the update server.
Tonight it worked. apologies for responding too early.

**Comment by mdegat01** [comment]
So there was a particularly bad bug around handling of network settings that went unnoticed for a while. Basically when network settings were updated from supervisor it blew away all custom network manager configurations it did not understand for the network interfaces it managed (which is a lot, network manager is has [many options](https://developer-old.gnome.org/NetworkManager/stable/ch01.html)).

This problem was discovered in 2022.4.0 by #3528 since we auto-applied an update in order to apply current defaults for everyone with out of date configurations. The issue has since been fixed in #3570 but that won't restore what was lost it will simply keep it from being lost again.

Reading how @tdejneka solved it [here](https://github.com/home-assistant/supervisor/issues/3582#issuecomment-1107517238) makes me think this is a symptom of #3528 . But the one thing I'm not understanding is how the DNS server information could've been lost. That is a setting that supervisor understands, it should show up in the network information of the supervisor panel and when you run the `ha network info` command.

If the issue is simply the DNS server is missing you should be able to tell from the network info in the [supervisor info panel](https://my.home-assistant.io/redirect/supervisor_info/) and you should be able to fix it from there as well. If adding a DNS server there does not actually set the DNS server for your network interface then please let me know as that is a bug that needs to be fixed.

Also if anyone is on the beta for 2022.5 then my supervisor info panel link won't work since network information moved. Instead you'll need to go to Configuration -> System -> Network. Sorry I can't make a my link for that yet since its not out yet.

**Comment by ausfestivus** [comment]
I can confirm I am seeing the same behaviour. You can see some information here https://discord.com/channels/330944238910963714/944337294389805056/990871542634262588.
