### ISSUE TITLE
Supervisor cant initiate after auto update

### ISSUE THREAD

**Issue by MrSolo570** [home-assistant/supervisor#3741]
### Describe the issue you are experiencing

Apparently supervisor auto updated 2 days ago (because it says the container was created 2 days ago). Ever since, the docker container tries to /init but carshes after few seconds (exited 0).
I can manually start other docker containers like home assistant or certain addons but obviously the system doesnt run core functions anymore without supervisor

### What is the used version of the Supervisor?

supervisor-latest (idk because I can't check anymore)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Raspbian 10 (buster)

### What version of Home Assistant Core is installed?

core-2022.6.7

### Steps to reproduce the issue

1. reboot host manually
2. automatically docker tries to start the docker container for supervisor, at my machine its called "hassio_supervisor"
3. after a few seconds the container exits with code 0 - trying to start again. this goes on forever
![650bcfbc014827400c10b03d2ab9baf97c4b746b](https://user-images.githubusercontent.com/61246489/179048684-3bb8612c-a772-4fd2-a238-ad5d9e747be0.jpeg)

...

### Anything in the Supervisor logs that might be useful for us?

```txt
it says: Failed to get supervisor logs, 502: Bad Gateway
```

**Comment by MrSolo570** [comment]
I have re-run the install script, didnt help

**Comment by mdegat01** [comment]
Not sure what installation script you're referring to but it's probably out of date since you're running in an unsupported system.

I would guess you're running on the incorrect docker version since that seemed to be the frequent root cause in [this thread](https://community.home-assistant.io/t/latest-supervisor-wont-start/437311). If you can't find your solution in there then I would suggest adding a post to that thread or making a new thread to see if there are other users in the same situation with your particular unsupported configuration. But first you will need to collect logs.
