### ISSUE TITLE
Upgrade does not validate config files first

### ISSUE THREAD

**Issue by theshaun** [home-assistant/supervisor#3803]
### Describe the issue you are experiencing

Likely a rare scenario, but I was updating my configuration.yaml and then let HASS update to the latest version.

My config had a type on a secret, which a normal reboot would have checked the config and warned me.

Should this be a check added to the upgrade process?

### What is the used version of the Supervisor?

2022.08.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

2022.8.5

### What version of Home Assistant Core is installed?

2022.8.5

### Steps to reproduce the issue

1. Update configuration.yaml with incorrect secret name
2. Start an outstanding upgrade
3. System moves to safemode

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

**Comment by mdegat01** [comment]
This isn't possible. Even if a config check passed it wouldn't mean anything. You're changing the version which means what is a valid config is also changing. Your config could pass the check and then you still end up in safemode because your previously valid config isn't valid anymore.

This is the purpose of safemode. If you update or restart and your config is bad then it starts HA anyway and provides guidance on what to do. So the fact that it started in safemode and guided you to the fix means everything is working as intended.
