### ISSUE TITLE
"Unhealthy" state can't be recovered remotely in a default setup

### ISSUE THREAD

**Issue by ssg** [home-assistant/supervisor#3908]
### Describe the issue you are experiencing

I also filed an issue on core repository about this (https://github.com/home-assistant/core/issues/78973). When a power cycle happens at home, Internet usually comes back up later than RPi4+HassOS. That apparently forces a "Unhealthy" state as I understand (because the documentation is very limited and mostly specific to certain components).

When RPi4+HassOS becomes Unhealthy, it's impossible to fix that state remotely using the UI. Only fix option is to use "Terminal & SSH" add-on, which isn't available in a default setup. You can't even install that add-on after the fact because add-on installs are blocked by Unhealthy state.

Restarting HA Core doesn't fix this issue. Restarting HA Supervisor isn't available in the UI.

This is such an unacceptable problem in the operating flow of Home Assistant. I say, HA Supervisor should be able to automatically recover from problems created by missing Internet connection during startup. It should never require manual intervention. Unhealthy should explicitly be reserved for truly unrecoverable phases. 

### What is the used version of the Supervisor?

supervisor-2022.09.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

There's no supervisor panel, and System tab doesn't show this information.

### What version of Home Assistant Core is installed?

core-2022.9.5

### Steps to reproduce the issue

1. Experience power loss at home.
2. Supervisor becomes Unhealthy.

### Anything in the Supervisor logs that might be useful for us?

```txt
Failed to to call /addons/core_ssh/install - 'AddonManager.install' blocked from execution, system is not healthy
```
```


### Additional information

_No response_

**Comment by mdegat01** [comment]
Hm so I took a device with HAOS on it, unplugged the ethernet cable and rebooted it. When I do that I see it has an issue, it tells me it could not execute the integrity check (which makes sense, that requires internet access). But it says it is both supported and healthy.

So I tried to simulate a power loss and pulled out the power on my dev system with the ethernet cable unplugged. Same result:
```
issues:
- context: system
  reference: null
  type: trust
  uuid: 3b4b69fde967469497592c46f4af4ea7
suggestions:
- auto: true
  context: system
  reference: null
  type: execute_integrity
  uuid: d9542f6b471546c0a8073b0cb5a466b0
unhealthy: []
unsupported: []
```
What is the reason the system is saying it is unhealthy?

**Comment by ssg** [comment]
The Repair panel said the issue was with "setup". But clicking on it only redirected me to the relevant Supervisor wiki about setup component which wasn't helpful in this case.

I assumed that this was an issue with power cycle because it happened after a power cycle. I read about the "not having Internet connectivity" causing health problems as there's very sparse information in the official docs.

Unplugging RPi4 and plugging it back fixed the issue, but impossible to do this remotely obviously.

**Comment by mdegat01** [comment]
Hm yea setup is not a specific one. That's more of a catchall that something went wrong during setup. The supervisor logs could probably give some insight at that point but they won't be accessible from the UI if its failing during setup. If you can attach a monitor and keyboard you can get to the supervisor logs without going through the UI by executing the following command:
```
docker logs hassio_supervisor
```
This command can also be executed from the SSH addon in the community add-ons repo with protection mode disabled, not the one in the official add-ons repo.

> Unplugging RPi4 and plugging it back fixed the issue, but impossible to do this remotely obviously.

Don't do this ever? It is a very bad idea to simply pull the power on a computer. They do their best to recover but its not a given. You are 100% losing data every time you do this as nothing is given a chance to flush caches to disk. Possibly a lot of data depending on how high you have [commit interval](https://www.home-assistant.io/integrations/recorder/#commit_interval) set to. And you risk permanent data corruption requiring a full wipe and reinstall of the OS each time.

I did it above to test this specific bug. And even then I would only ever do it on a dev system since I wipe and reinstall those regularly anyway.

Tbh if you have been doing this a lot then data corruption might be the root cause here. I was assuming power cycle was an edge case, perhaps not. Definitely don't pull the power yourself. And if you lose power a lot then consider investing in an uninterruptible power supply so your devices are given a chance to cleanly shut down.

**Comment by ssg** [comment]
After fixing the problem, I was able to install SSH add-on and now I've got terminal access to it. There's no `docker` command accessible through this SSH though. Attaching display and keyboard to RPi4 isn't possible remotely either.

There was no useful information in `ha supervisor logs`. I guess those get cleaned up after every restart.

> Don't do this ever? It is a very bad idea to simply pull the power on a computer. 

Yes, it's not the ideal approach; but, for an application like Home Assistant, power loss, reboots, disconnections are part of life. HA should expect sudden power loss as part of its regular operational flow. Losing some log data etc is okay in this case, but turning full "Unhealthy" is unacceptable.

I think that you put too much emphasis on the possibility of data corruption. Why did a power cycle fix the health issue then? If there was a corruption, the corrupt data should have remained corrupt after the reboot and the device should have remained unhealthy.

Regardless of my own experience, the issue still stands which is the reason I filed it: *It's impossible to recover from "Unhealthy" state remotely if SSH addon isn't installed*. There's a design problem here. This flow is broken. My own power cycling habits are irrelevant.

**Comment by mdegat01** [comment]
> There's no docker command accessible through this SSH though.

Which SSH addon did you install. There's two

> This command can also be executed from the SSH addon in the *community add-ons repo with protection mode disabled*, **not** the one in the official add-ons repo.

> It's impossible to recover from "Unhealthy" state remotely if SSH addon isn't installed.

Yes but unhealthy is also really bad, it's not a state anyone is supposed to get into. There's actually only [4 reasons you can be unhealthy](https://github.com/home-assistant/home-assistant.io/tree/current/source/more-info/unhealthy) and the other 3 all require ssh to get into in the first place. Or at least host shell access. Setup is the only one that's rather generic and simply calls out a fatal issue in a particular window rather then a specific and clear issue.

You're right that rebooting with or without internet should not make it unhealthy, something does seem to be going wrong if that's happening. For reference I'm not actually asking you to install the SSH addon so you can fix it, I'm asking so I can see what actually went wrong during startup. There may very well be a bug to fix here rather then something for you to do to your system.

> HA should expect sudden power loss as part of its regular operational flow.

HA isn't really the problem here. HA actually does prepare for sudden unexpected stops. If you force kill any of the containers for example they will come to an immedate and unexpected halt and yet will recover just fine. The problem under all that is a linux system. Linux (like any modern OS) does plan for power loss events and will do its best to recover from it but its not a guarantee. HA doesn't have any say in that.

**Comment by mdegat01** [comment]
> or add a "reboot Host OS" option in the menu.

This already exists. Go to [Settings -> System -> Hardware](https://my.home-assistant.io/redirect/hardware/), click the 3 dots in the top right and do "Reboot Host":
![Screen Shot 2022-09-29 at 2 47 46 PM](https://user-images.githubusercontent.com/2037026/193117042-84b21d31-b94d-4031-919e-d326e3072af2.png)

Also just an FYI this is in [the link](https://www.home-assistant.io/more-info/unhealthy/setup). Immediately after it suggests running `ha supervisor restart` it says this:
> If this does not help, you can try to reboot the host. If you are running Home Assistant Operating System, this can be done from the “System” tab in the Supervisor panel. On the card for “Host System”, there is a button to reboot the host.

If you find the wording confusing you're welcome to propose an update, there's an edit button right at the bottom of that page.

**Comment by ssg** [comment]
Thanks @mdegat01, yes, I wasn't able to find this option. Updating the docs would be great. I appreciate your help.
