### ISSUE TITLE
Repeating Error in the Supervisor Logs trying to send information to Sentry.io without my permission

### ISSUE THREAD

**Issue by jweston2112** [home-assistant/supervisor#3973]
### Describe the issue you are experiencing

I am getting an Error repeatedly in the Supervisor Logs

```
22-10-26 01:52:42 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9074b3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/5370612/envelope/
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I have rebooted and Restarted  Supervisor (ha su restart)

### Anything in the Supervisor logs that might be useful for us?

```txt
22-10-26 01:52:42 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9074b3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/5370612/envelope/
```

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4723
Installed Version | 1.28.3
Stage | running
Available Repositories | 1140
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.10.1
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 228.5 GB
disk_used | 11.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Node-RED (13.4.0), SSH & Web Terminal (12.0.2), MariaDB (2.5.1), Studio Code Server (5.4.0), Glances (0.16.0), Samba Backup (5.2.0), Log Viewer (0.14.0), ArgonOne Active Cooling (28d), ESPHome (2022.10.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 10
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 23, 2022 at 5:00 AM
-- | --
current_recorder_run | October 26, 2022 at 1:50 AM
estimated_db_size | 173.02 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Supervisor diagnostics

[config_entry-hassio-b20a568cb4d1e3c68d96d3ee7f3f12f1.json.txt](https://github.com/home-assistant/supervisor/files/9866627/config_entry-hassio-b20a568cb4d1e3c68d96d3ee7f3f12f1.json.txt)

**Comment by mdegat01** [comment]
So this is sentry. Sentry is the tool we use for collecting diagnostic information from systems with diagnostics enabled in [Settings -> System -> Analytics](https://my.home-assistant.io/redirect/analytics/). I don't really know why that's failing, if you go to https://sentry.io/ on some other system on your network does it work?

Also as a test could you ssh into HA and share the results of these commands?
```
dig A sentry.io
dig AAAA sentry.io
```

**Comment by jweston2112** [comment]
Well to be honest I found an entry in my PiHole Query Log that its blocking 

o427061.ingest.sentry.io
--

from my "Test/Beta" ha instance... so I went and started looking in my supervisor logs and found these errors

it seems to be repeating it 3 times once a minute
 
its not happening on my Production machine... so is this something new in Supervisor 2022.10.1 and Later??? 

I guess the real question is ... is there a way to see why it wants to send something.... especially after I turned off the analytics and did a ha su restart and ha core restart

I would imagine that takes a few cpu cycles...

**Comment by neckyaan** [comment]
many advertisement blocking software have closed the nslookup of sentry.io. After I modified the blocking rules, everything was normal.

**Comment by Tamsy** [comment]
> After I modified the blocking rules, everything was normal.

Calls to the mothership shouldn't happen without user consent in the first place.

There is another issue report about the latter [here](https://github.com/home-assistant/core/issues/81566).

**Comment by jweston2112** [comment]
I concur with Tamsy here ... while I had been sharing analytics with them when I turned it off and still getting the error messages seems to me they may have started taking some liberties on their own... 

I also think there is certain lack of clarity in the above mentioned error....
something like :
"While attempting to report an error for integration X  for error reason Y we encountered the following error trying to send the diagnostic information.
>> sentry.io message"

and if you are pinging sentry.io to see if its still there .... stop wasting my bandwidth and slowing my automation server.

**Comment by pvizeli** [comment]
We do not send any data without permission. Seems they are changing the library and doing somethings but at least they send nothing to us. I will open an issue on sentry that they fix there library and not make a request for whatever if we anyway don't send data then

**Comment by jweston2112** [comment]
Supervisor container also uses the Analytics Settings from Home Assistant??? Because it appears you are using sentry_sdk  in supervisor as well ... the errors I am seeing are in the Supervisor Log. So if supervisor is sending information and it does not honor the HA Analytics Settings... then you ARE sending information with out my permission .

The error messages above are making the Supervisor log unusable as well...

**Comment by mdegat01** [comment]
So I mean quick rundown of the way it works. In the [analytics panel](https://my.home-assistant.io/redirect/analytics/) (screenshotted above), when you disable "diagnostics" it tells supervisor that. You can confirm that diagnostics have been disabled in supervisor using the cli by doing `ha supervisor info`. One of the fields in the response is `diagnostics`, it should be `false` if you have turned that toggle off on the analytics screen.

On startup supervisor sets up diagnostics reporting here:
https://github.com/home-assistant/supervisor/blob/a2dffe595e57fb2ddc0cdae89c702354f524b2b2/supervisor/bootstrap.py#L321-L340

Notice that events filter it adds. That's this bit of code that is run on the event before anything is sent off to sentry:
https://github.com/home-assistant/supervisor/blob/a2dffe595e57fb2ddc0cdae89c702354f524b2b2/supervisor/misc/filter.py#L25-L35

If diagnostics is off, the event is automatically filtered it out. This is how the system has worked for some time, all events are filtered out if the user turns off diagnostics.

Although as pvizeli noted above we do rely on the library. It's possible there's a bug causing it to send something even when we filter out all meaningful data here. Or possibly its testing for existence of the server in the background now (since it sounds like you're seeing a consistent pattern of calls). We'll follow up if so. But there's nothing intentional about this and supervisor is still filtering out all meaningful data from anything being sent with the logic I showed above.

**Comment by jweston2112** [comment]
So to be clear.... it still makes a connection (when my ad blocking DNS doesn't interfere ) and sends an "empty envelope" or does the event get ignored and usually no connection at all is made?

Id also like to point out that this issue was opened 2 weeks ago... before it was rolled out to the stable group... this might have been addressed then and not affected a number of people....

**Comment by pvizeli** [comment]
> Id also like to point out that this issue was opened 2 weeks ago... before it was rolled out to the "stable" group... this might have been addressed then and not affected a number of people....

This is an opensource project and everyone is welcome. There is no free support it's a work of all. Second we looked into the library and it doing kinda system check since we use this library, which is I guess now 3years. I don't see that this thread is 3years old, right? All is opensource from this code to the library. Instead to talking bullshit, you can read the code and doing a correct analytic of the issue and not doing fake news.

**Comment by jweston2112** [comment]
Sorry this upsets you pvizeli ... I understand this is all open source software... I dont know python (well at the level you guys write at )  .. I do appreciate the python lesson from mdegat01 and taking the time to explain it. It started off as an attempt to bring to light something I discovered while it was still in the beta group... I guess you could say in some small way I was trying to contribute...the original title was kind of inaccurate so I updated it to make it more clear and potentially draw a bit more attention once I discovered it was still attempting to connect after I turned off the analytics settings... sentry-sdk for python is also a open source software and I have been looking through their code on github as well  ( to see if I could figure out what info they collect in the basic envelope --- I use that term as that seems to be what they call it)

I didnt realize till this issue that you (well not you specifically... home assistant) sends this data to a third party (even though the analytics web page plainly states that) had I realized that I would not have opted in at all... 

in as far as insinuating it was intentional... I believe I usually tried to phrase it all as questions...not to imply guilt or fault 

perception is reality... a very small reality when you have very little insight to the behind the scenes goings on...trying to piece together what happened and when it will get fixed with little or no feedback for some time .... you could say that is frustrating 

but I still have a supervisor log getting updated every minute with 3 failed connection attempts...  wiping out any usable feedback in the log .... that makes it useless...  

once again sorry this upsets you.

**Comment by mdegat01** [comment]
Since it is logged at warning level if it is making the logs useless what you can do for now is enter this in the cli:
```
ha supervisor options --logging error
```
This will set supervisor's log level so you won't see these. Obviously this will cause you to miss out on other info and warning level logs but it sounds like that is already happening. And after this you will see the more critical things at error and above.

That's not a solution by any means, just a workaround to get your log usable again. I'm going to work on a real fix since it seems it isn't safe to load sentry at all anymore if diagnostics are off. Fwiw given the pattern of logging you are describing I'm pretty convinced this is a new connectivity check rather then empty events being sent. Errors and exceptions don't generally occur in a regular repeating pattern or with such frequency else you would be seeing a lot of other issues.

**Comment by jweston2112** [comment]
I concur with the connectivity check seems that does make sense ... I got into ssh Terminal and did "docker stats" and the supervisor was routinely jumping up to 7-8% CPU... not sure if thats normal or not but the timing did seem about right for the checks... I guess one of my concerns was that if the log is getting written to that often would it fill the drive and potentially crash... hasnt yet... but I have no idea where to look for it.... Thanks for your assistance...

**Comment by jweston2112** [comment]
Supervisor 2022.11.1 has resolved this issue for me 

* no raven-sentry error messages in supervisor log
* no Pihole query log entries for the machine with the update
* added bonus cpu utilization 2-3% lower while idling

**Comment by dotgrid** [comment]
I just wanted to say a big **THANK YOU** to everyone who contributed to this issue.

Like the other users who commented, I felt confused and uncomfortable seeing those outbound Sentry.io connections—it felt very _unlike_ the Home Assistant we know and love ❤️ 

I _really_ appreciate @mdegat01 (and the wider Home Assistant team) listening, clarifying, and expending their valuable time to engineer a solution. 🎉 :shipit: 

**Thank you.**
