### ISSUE TITLE
HomeAssistant sends 15-20 req per *second* to 1.1.1.1 and 1.0.0.1

### ISSUE THREAD

**Issue by kiler129** [home-assistant/supervisor#4016]
### Describe the issue you are experiencing

While DNS is surely important for HASS contacting a 3-rd party provider without my constant is not cool. However it looks like this is [ignored](https://github.com/home-assistant/supervisor/issues/2139) and not seen as a [privacy problem](https://github.com/home-assistant/supervisor/issues/2437). Fair enough, but why is HASS essentially performing a **SYN flood attack**:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/1227834/203453300-af025e55-9b80-4da9-8cc8-eb1018d904b5.png">

`ha dns logs` confirms that indeed it's HASS making these requests in some sort of a loop:
![image](https://user-images.githubusercontent.com/1227834/203453375-53f0363f-5ab6-4675-bcba-059d2c1faa4f.png)

This to me seems like at least a bug - it shouldn't be happening 15-20x a second. Moreover HASS receives and uses the DHCP-provided DNS, so there's completely no reason for the instance to query `1.1.1.1` and `1.0.0.1`.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Block outbound connections from HASS to `TCP/853`
2. Observe outgoing traffic

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

**Comment by jweston2112** [comment]
ha dns options --fallback=false (in a SSH session where the cli is available)

seems to have stopped it for me of course if you run into issues you can set it back to true...

**Comment by rapi3** [comment]
> ha dns options --fallback=false (in a SSH session where the cli is available)
> 
> seems to have stopped it for me of course if you run into issues you can set it back to true...

Can you please give us more details what/where it is located config file to be edited.
thank you

**Comment by jweston2112** [comment]
You would need to have the addon SSH & Web Terminal installed ... 

at the prompt you would type in the line : ha dns options --fallback=false 

that sets the flag to not use the fallback dns hardcoded in the software (I guess it was done this way to help some people who were having serious dns / name resolution issues. They do use TLS to encrypt and obscure the requests)

it **_does_** persist after a reboot (I just checked)... I believe the file it updates is in the root filesystem that you can only see if you have setup SSH to the OS ... is /mnt/data/supervisor/dns.json but you should only use the CLI  command I specified above to avoid trashing the config...as it may make other changes elsewhere that I am not aware of. 

```
# cat dns.json
{
  "fallback": false,
  "servers": [],
  "version": "2022.04.1",
  "image": "ghcr.io/home-assistant/amd64-hassio-dns"
}# 

```


the link you provided pretty much explains it all...

**Comment by kiler129** [comment]
The `ha dns options --fallback=false` indeed seems to stop the DoS. However, imo the bug still stands - it shouldn't try the fallback 15x/sec ;)

**Comment by jweston2112** [comment]
Well I agree that seems pretty high ... but it probably has more to do with the combinations of integrations and add-ons all making the requests for name resolution and how they meter their attempts ... the DNS is just gonna try to process as fast as possible...the logfile (at least at the default logging level) doesnt specify the requester ... my question would be...  why the heck did it need to "fallback" so frequently??... especially when I turned off the fallback and all my stuff still seems to be running fine... seems like the test (IF Statement) is always resolving to true or being skipped and just using the fallback(as well as regular lookups) ... just a guess but probably should be looked into anyway

**Comment by redgryphon** [comment]
This is a well known behavior that is generated by the DNS plugin, not the supervisor itself. See home-assistant/plugin-dns#90.
It has been partially fixed by #3586, though.

**Comment by mdegat01** [comment]
This isn't really something Supervisor can do much about to be honest. Internally HA uses [CoreDNS](https://coredns.io/) to handle DNS requests. And as noted above, it uses DoT to Cloudflare's DNS as a fallback by default. There are good reasons for this fallback, if you want to learn more about why it exists read my post [here](https://community.home-assistant.io/t/local-dns/178108/119?u=centralcommand).

The problem is CoreDNS rightfully never anticipated the situation where a user has specified a DNS server that they have blocked on their network. It assumes if it can't reach a specified DNS server at all that is a serious problem. I guess it handles it in the way you see above (supervisor definitely has not intentionally set anything to spam that many requests a second anywhere).

So Supervisor did the only thing that was in its control - allow users to disable the fallback DNS. This way the only DNS servers used are what they configure. Its possible you will run into some issues if your DNS server is not following spec correctly around AAAA requests (see my posts for what I mean). But if your going to block HA's access to port 853 on your network then you need to disable the fallback DNS in the CLI with the command shown above (copied here for reference):
```
ha dns options --fallback=false
```

**Comment by KevinCathcart** [comment]
@mdegat01 said:
> Supervisor definitely has not intentionally set anything to spam that many requests a second anywhere

Yes, but supervisor (or more accurately the dns plugin's corefile) has _unintentionally_ set something that due to some unfortunate interactions with other parts of coreDNS happens to be causing this. 

Basically a harmless-seeming setting would cause something like this to happen for 5 seconds after each NXDOMAIN if Cloudflare DoT is being blocked. But then in conjunction with how the `fallback` plugin internally uses the `forward` plugin which has health checks by default, every 0.5 seconds that 5 second burst starts again. For details see [my latest post in that other issue](https://github.com/home-assistant/plugin-dns/issues/90#issuecomment-1413110174). 

I don't fully spell it out all the details in super great depth, so please feel free to ask questions, but I've spent many hours investigating and typing up details about that issue without even being affected, since it tangentially impacts something I do care about.

Now obviously, turning off the fallback is the easy fix for end users who don't have the issue where the fallback is needed.
