### ISSUE TITLE
Unsupported Install

### ISSUE THREAD

**Issue by B3nihana** [home-assistant/supervisor#4121]
### Describe the issue you are experiencing

My install is complaining since the last core update to 2023.1.7 that it is not a supported install, specifically the below issues are mentioned.

Unsupported system - Systemd issues
Unsupported system - Operating System
Unsupported system - CGroup version

I am running HASS OS on an RPi 3B with a Conbee II USB.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Install HASS OS on RPI 3B, update everything to latest releases.

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-27 13:36:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-27 13:36:20 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 13:36:20 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 13:42:23 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-27 13:42:23 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-27 13:42:23 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-27 13:42:23 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-27 13:42:23 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-27 14:06:07 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-27 14:35:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-27 14:35:54 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-27 14:36:07 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-27 15:06:08 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-27 15:35:54 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-27 15:35:55 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-27 15:35:55 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-27 15:35:55 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-27 15:36:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-27 15:49:03 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-27 15:49:03 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-27 15:49:03 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-27 15:49:03 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-27 15:49:03 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-27 16:06:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-27 16:18:16 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-01-27 16:18:16 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-01-27 16:18:16 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-27 16:18:16 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-27 16:18:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 16:18:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 16:18:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-27 16:18:26 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-27 16:18:26 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-27 16:18:26 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-27 16:18:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-01-27 16:18:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-01-27 16:18:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-27 16:18:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 16:18:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 16:25:11 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
23-01-27 16:25:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-01-27 16:25:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-01-27 16:25:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-27 16:25:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-01-27 16:25:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
```

## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 13.9 GB
disk_used | 7.6 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.12.8), InfluxDB (4.5.0), Grafana (8.1.0), deCONZ (6.18.0), Google Assistant SDK (2.5.0), Mosquitto broker (6.1.3), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 January 2023 at 12:02
-- | --
current_recorder_run | 26 January 2023 at 16:51
estimated_db_size | 76.62 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Supervisor diagnostics

[supervisor_2023-01-27T15-26-11.188Z.log](https://github.com/home-assistant/supervisor/files/10520356/supervisor_2023-01-27T15-26-11.188Z.log)

**Comment by j21w91** [comment]
same

**Comment by rainersdot** [comment]
same

**Comment by B3nihana** [comment]
Issue still exists as of the latest updates:
Home Assistant 2023.3.1
Supervisor 2023.01.1

**Comment by MosaKiswani** [comment]
same problem still exists,

**Comment by B3nihana** [comment]
Happy to say that the warnings for me have gone in the latest update, I'm now running:

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

Will leave open for others to confirm.

**Comment by AubsUK** [comment]
> warnings for me have gone in the latest update

They had gone for me, but I think tonight they came back.

I installed with a fresh download on ‎12 ‎March ‎2023 (then imported a backup) using `haos_generic-aarch64-9.5.vmdk.zip` from https://github.com/home-assistant/operating-system/releases/tag/9.5

I have it running on a VM in ESXi on Arm Fling on RPi 4 8GB

Happy to provide any information that might be useful.

# Unsupported Warnings

### Unsupported system - Operating System
System is unsupported because the operating system in use is not tested or maintained for use with Supervisor. Use the link to which operating systems are supported and how to fix this.
Warning - 23/03/2023

### Unsupported system - Systemd issues
System is unsupported because Systemd is missing, inactive or misconfigured. Use the link to learn more and how to fix this.
Warning - 23/03/2023

### Unsupported system - CGroup version
System is unsupported because the wrong version of Docker CGroup is in use. Use the link to learn the correct version and how to fix this.
Warning - 23/03/2023

# Latest Install

### Current Versions
Home Assistant 2023.3.6
Supervisor 2023.03.3
Frontend 20230309.1 - latest

### Backup Created
core_2023.3.4
Partial backup (47.7 MB)
25 March 2023 at 13:13
Home Assistant
(2023.3.4)

# System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1315
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 19.0 GB
disk_used | 6.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Mosquitto broker (6.2.0), Node-RED (14.1.3), Nginx Proxy Manager (0.12.3), MariaDB (2.5.2), NGINX Home Assistant SSL proxy (3.2.0), File editor (5.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 5
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 March 2023 at 13:18
-- | --
current_recorder_run | 25 March 2023 at 13:24
estimated_db_size | 200.24 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

# Additional Update
## Performed a full system reboot at 23:39 (before the above), and so far, 15 hours later at the time of posting (14:38), showing as supported.  So it appears restarting HA isn't sufficient and a full system reboot may be required.

### System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1315
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 19.0 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | generic-aarch64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Mosquitto broker (6.2.0), Node-RED (14.1.3), Nginx Proxy Manager (0.12.3), MariaDB (2.5.2), NGINX Home Assistant SSL proxy (3.2.0), File editor (5.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 5
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 March 2023 at 13:18
-- | --
current_recorder_run | 30 March 2023 at 23:39
estimated_db_size | 204.23 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by frenck** [comment]
Multiple confirmations, going to close this issue for now.

../Frenck

**Comment by teaserrr** [comment]
Can this be reopened? I started seeing these 'unsuppported' warnings a couple of days ago, while running 2023.6.1. This version had already been installed for several days, so the warnings didn't appear right after an update. I also did not install any integrations, add-ons or do any other modifications to HA or my system when the warnings appeared. There was a supervisor update pending before the notifications appeared, which is now gone, but I'm pretty sure I didn't start that update. 

This morning I installed core 2023.6.2 which didn't solve the issue.

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1284
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 29 augustus 2023 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-3.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 28.6 GB
disk_used | 10.0 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba Backup (5.2.0), Advanced SSH & Web Terminal (15.0.2), ESPHome (2023.5.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 juni 2023 om 09:48
-- | --
current_recorder_run | 16 juni 2023 om 10:51
estimated_db_size | 750.02 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by teaserrr** [comment]
Ok after a reboot of the system the warnings are gone and the OS update is available again, which I'm running now.
