### ISSUE TITLE
Mounting to Network Share Failed using guest

### ISSUE THREAD

**Issue by mrslvd** [home-assistant/supervisor#4356]
### The problem

I can't connect Home Assistant to  samba share.
I got USB drive connected to Asus router. Guest login is allowed and no user and pass is needed.
When I type \\192.168.0.1\ext1 to windows explorer I can access this share.
I can use this share from all other devices in my network. For example media players, android mobiles, TV set top boxes.

### What version of Home Assistant Core has the issue?

2023.6

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Jun 08 17:13:08 homeassistant systemd[1]: Mounting Supervisor cifs mount: wrt...
Jun 08 17:13:08 homeassistant kernel: CIFS: Attempting to mount \\192.168.0.1\ext1
Jun 08 17:13:08 homeassistant mount[7193]: Password for root@//192.168.0.1/ext1:
Jun 08 17:13:08 homeassistant mount[7192]: mount error(22): Invalid argument
Jun 08 17:13:08 homeassistant mount[7192]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 08 17:13:08 homeassistant systemd[1]: mnt-data-supervisor-mounts-wrt.mount: Mount process exited, code=exited, status=32/n/a
Jun 08 17:13:08 homeassistant systemd[1]: mnt-data-supervisor-mounts-wrt.mount: Failed with result 'exit-code'.
Jun 08 17:13:08 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: wrt.
Jun 08 17:13:08 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
```

### Additional information

![image](https://github.com/home-assistant/core/assets/67948421/4af86cb5-4b6b-43e6-9bca-5c84e8f65ba1)
![image](https://github.com/home-assistant/core/assets/67948421/6c36ed64-0e68-4cf4-8e40-c72fcfbb7a10)

**Comment by Anto79-ops** [comment]
Hi. I have the same issue with same error message (mount error).

I can connect to my USB drive connected to my router in Windows but cannot connect via HA.

**Comment by markli96** [comment]
Hi, I have to same problem and I think the problem is in smb version - https://askubuntu.com/a/962862. But I don't know what to do about it 😄

**Comment by ludeeus** [comment]
No, that is not the same. For CIFS we currently do not support guest access (what this issue is about).

For version, you need to be running 2.1+ on your NAS.
"-22" error, means _something_ was wrong, it's a catch-all error.

**Comment by Anto79-ops** [comment]
hmm... I'm trying to figure out to determine the version on my router, I think its at least 2.0. Its Linksys WRT3200ACM running stock firmware. Guess I might have to upgrade to DD-WRT....now?

**Comment by ludeeus** [comment]
Still unrelated here, this is about _guest_ access..

**Comment by Anto79-ops** [comment]
ahh, ok, when you say guess access do you mean _guest_ username? It does not work for anything in the username or password, even blank fields.

**Comment by ludeeus** [comment]
> I got USB drive connected to Asus router. Guest login is allowed and no user and pass is needed.

**Comment by Anto79-ops** [comment]
thanks for clarifying.

I'd be curious to know if the op also has the same issue with non-guest access...i,e. create username and password and try again.

**Comment by markli96** [comment]
Hi, I don't know if I should create a new issue, but I am having the same problem when using guest access and also when using username and password. 

I have just purchased TP-Link AX55 and I tried to find, what SMB it supports and it should be version 2. But I don't know if it is 2.0 or 2.1+.

When I use **guest mode**, the log looks like this:

> Jun 10 06:52:00 homeassistant systemd[1]: Mounting Supervisor cifs mount: TPLinkShare...
Jun 10 06:52:00 homeassistant kernel: CIFS: Attempting to mount \\192.168.2.1\G
Jun 10 06:52:00 homeassistant mount[234819]: Password for root@//192.168.2.1/G:
Jun 10 06:52:00 homeassistant mount[234818]: mount error(22): Invalid argument
Jun 10 06:52:00 homeassistant mount[234818]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 10 06:52:00 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
Jun 10 06:52:00 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Mount process exited, code=exited, status=32/n/a
Jun 10 06:52:00 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Failed with result 'exit-code'.
Jun 10 06:52:00 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: TPLinkShare.

And when I use **username and password** it looks like this:

> Jun 10 06:56:35 homeassistant systemd[1]: Mounting Supervisor cifs mount: TPLinkShare...
Jun 10 06:56:35 homeassistant kernel: CIFS: Attempting to mount \\192.168.2.1\G
Jun 10 06:56:35 homeassistant mount[236248]: mount error(22): Invalid argument
Jun 10 06:56:35 homeassistant mount[236248]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 10 06:56:35 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
Jun 10 06:56:35 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Mount process exited, code=exited, status=32/n/a
Jun 10 06:56:35 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Failed with result 'exit-code'.
Jun 10 06:56:35 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: TPLinkShare.




The network folder \\\192.168.2.1\g is accessible via windows file manager.
![image](https://github.com/home-assistant/supervisor/assets/34098645/6f627220-38c1-40b7-95d2-5ae618ff9d9e)


![image](https://github.com/home-assistant/supervisor/assets/34098645/7d2123e0-eead-47b0-8787-6a3b52d19cbe)
![image](https://github.com/home-assistant/supervisor/assets/34098645/6c500717-5c7b-491d-ad45-c54fa4fc5b7f)


And here is my router settings:
![image](https://github.com/home-assistant/supervisor/assets/34098645/d19188ee-c0ee-4808-b961-b095b911bb65)
![image](https://github.com/home-assistant/supervisor/assets/34098645/eb5bdaac-9b95-4ca8-bf8b-ff8c6c13d534)




I have tried to **use //TPShare instead of router IP address (192.168.2.1)**, but the home assistant cannot resolve the domain address.

> Jun 10 07:06:54 homeassistant systemd[1]: Mounting Supervisor cifs mount: TPLinkShare...
Jun 10 07:06:55 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c29cbc5cac75c6e24aff381328f982a1d31790f4f1c788c1976286a659b5e26f-runc.dKe0GS.mount: Deactivated successfully.
Jun 10 07:06:58 homeassistant mount[238429]: mount error: could not resolve address for TPShare: Unknown error
Jun 10 07:06:58 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Mount process exited, code=exited, status=1/FAILURE
Jun 10 07:06:58 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Failed with result 'exit-code'.
Jun 10 07:06:58 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: TPLinkShare.




I hope this will help someone to fix this. Thank you in advance.

**Comment by markli96** [comment]
And just to let you know. I have tried it today again and there was additional message in the host log.

> Jun 12 06:58:01 homeassistant systemd[1]: Mounting Supervisor cifs mount: TPLinkShare...
Jun 12 06:58:01 homeassistant kernel: Key type cifs.spnego registered
Jun 12 06:58:01 homeassistant kernel: Key type cifs.idmap registered
Jun 12 06:58:01 homeassistant kernel: CIFS: No dialect specified on mount. Default has changed to a more secure dialect, SMB2.1 or later (e.g. SMB3.1.1), from CIFS (SMB1). To use the less secure SMB1 dialect to access old servers which do not support SMB3.1.1 (or even SMB3 or SMB2.1) specify vers=1.0 on mount.
Jun 12 06:58:01 homeassistant kernel: CIFS: Attempting to mount \\192.168.2.1\g
Jun 12 06:58:01 homeassistant mount[64087]: mount error(22): Invalid argument
Jun 12 06:58:01 homeassistant mount[64087]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 12 06:58:01 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
Jun 12 06:58:01 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Mount process exited, code=exited, status=32/n/a
Jun 12 06:58:01 homeassistant systemd[1]: mnt-data-supervisor-mounts-TPLinkShare.mount: Failed with result 'exit-code'.
Jun 12 06:58:01 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: TPLinkShare.

But when I try it again, the messages are the same as in my previous comment.

**Comment by ludeeus** [comment]
You are still off-topic here @markli96, you are using username/password, this issue is about _guest_ access.
Your problem is that your router is using too old SMB, you need 2.1 or higher.

**Comment by nstrelow** [comment]
I have the same 2 problems. Guest access, but also I only have smb v2.0.2
