### ISSUE TITLE
[HAssOS] Can't connect to the Synology shared folder as a domain user

### ISSUE THREAD

**Issue by ESP4Ever** [home-assistant/supervisor#4363]
### The problem

Hello!

When I'm trying to use the "Network Storage" feature it doesn't connect to my Synology NAS if I'm using domain credentials ( DOMAIN\username )

![image](https://github.com/home-assistant/core/assets/44872879/c54698a0-55f2-4a2c-adeb-6a1859b4b8ec)

### What version of Home Assistant Core has the issue?

2023.6.1

### What type of installation are you running?

Home Assistant OS

**Comment by ludeeus** [comment]
Check your host logs (as the error say) and make sure your NAS is running SMB 2.1+

**Comment by ESP4Ever** [comment]
Hello!
It's configured to support >=SMB2
There is no even a connection attempt from HA if the domain user login is used so the log is empty, the local user login is working fine.

**Comment by ludeeus** [comment]
I see, you _might_ be able to use `DOMAIN\\username` (double backslash), if not a `domain` option needs to be added to support it.

**Comment by Creepios** [comment]
> I see, you _might_ be able to use `DOMAIN\\username` (double backslash), if not a `domain` option needs to be added to support it.

Yes! I tried the double backslash but it doesnt work either. A domain option should be implemented.

**Comment by Creepios** [comment]
> This should work `workgroup/user` https://linux.die.net/man/8/mount.cifs

Sorry to say that but it doesnt works for me!

**Comment by Creepios** [comment]
After long and detailed investigation, I have come to the conclusion that it will be necessary to insert a "DOMAIN" field.

About my infrastructure:

My domain is: "MYDOMAIN".
Username: "niklas
Password: "1234"

I use TrueNAS as NAS system with SMB v4 and AD as authentication.

If I do it as the workaround suggests (i.e.: username: "MYDOMAIN/niklas"; password: "1234") then I get the following message in the SMB log on my TrueNAS server:



`{"timestamp": "2023-07-02T19:17:47.395107+0200", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 2}, "eventId": 4625, "logonId": "0", "logonType": 3, `
**"status": "NT_STATUS_NO_SUCH_USER"**, 
`"localAddress": "ipv4:xxx.xxx.xxx.xxx:445", "remoteAddress": "ipv4:xxx.xxx.xxx.xxx:41426", "serviceDescription": "SMB2", "authDescription": null, `
**"clientDomain": "", "clientAccount": "MYDOMAIN/niklas"**, 

`"workstation": "", "becameAccount": null, "becameDomain": null, "becameSid": null, `

**"mappedAccount": "MYDOMAIN/niklas", "mappedDomain": ""**, 
`
"netlogonComputer": null, "netlogonTrustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "NTLMv2", "duration": 1836}}`




The marked section shows that the mappedUser and mappedDomain cannot be recognized because AD accepts only the backslash and not the normal slash and also no domain can be assigned. This can also be applied to all other systems.
By a little research in the code you can quickly find the line in the supervisor:


(file "[supervisor](https://github.com/home-assistant/supervisor/tree/ee027eb510cf39912b4c207f4aaf3e092622fde8)/[supervisor](https://github.com/home-assistant/supervisor/tree/ee027eb510cf39912b4c207f4aaf3e092622fde8/supervisor)/[mounts](https://github.com/home-assistant/supervisor/tree/ee027eb510cf39912b4c207f4aaf3e092622fde8/supervisor/mounts)/mount.py" line 413-414)
`with self.path_credentials.open(mode="w") as cred_file:`
`    cred_file.write(f"username={self.username}\npassword={self.password}")`


With a little change according to the mount.cifs man documentation (https://linux.die.net/man/8/mount.cifs) you can enter the domain manually permanently in the code:
(Same file, same line)


`with self.path_credentials.open(mode="w") as cred_file:`
`    cred_file.write(f"username={self.username}\npassword={self.password}\ndomain=MYDOMAIN")`


This will give the following result on my NAS server:



`{"timestamp": "2023-07-02T19:42:02.626554+0200", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 2}, "eventId": 4624, "logonId": "0", "logonType": 3, `

**"status": "NT_STATUS_OK",** 

`"localAddress": "ipv4:xxx.xxx.xxx.xxx:445", "remoteAddress": "ipv4:xxx.xxx.xxx.xxx:50084", "serviceDescription": "SMB2", "authDescription": null, `

**"clientDomain": "MYDOMAIN", "clientAccount": "niklas",** 

`"workstation": "", `

**"becameAccount": "niklas", "becameDomain": "MYDOMAIN", "becameSid": "S-1-5-21-xxxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxx", "mappedAccount": "niklas", "mappedDomain": "MYDOMAIN",** 

`"netlogonComputer": null, "netlogonTrustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "NTLMv2", "duration": 11740}}`



Domain is mapped correctly and the user can be authenticated. Now the network storage is mounted. Of course it is not wanted to hardcode this manually into the code, so on urgent recommendation an optional domain field should be added. I would do this myself in a pull request, but unfortunately I don't have the time at the moment.

**Comment by Creepios** [comment]
@ludeeus sorry for the ping but I dont know if anybody sees this update that I posted to this issue if I'm not pinging

**Comment by ludeeus** [comment]
Someone sees it. There is nothing there we were not aware of already.

The reason it does not exist, is time.

**Comment by Creepios** [comment]
This issue still needed to be fixed.

**Comment by ESP4Ever** [comment]
This issue still needed to be fixed.

**Comment by Creepios** [comment]
This issue still needed to be fixed.

**Comment by Creepios** [comment]
This issue still needed to be fixed.
