### ISSUE TITLE
Network storage doesn't allow = sign in password

### ISSUE THREAD

**Issue by jourdant** [home-assistant/supervisor#4403]
### Describe the issue you are experiencing

I'm looking to mount an Azure Files share over SMB to my home assistant for backups. You can directly connect with details similar to:

```
Host: <account_name>.file.core.windows.net
User: localhost\<account_name>
Pass: This is either the primary or secondary storage key. Both keys end with == and therefore don't adhere to the regex rule that I have referenced in this issue.
```

As mentioned, the regex in https://github.com/home-assistant/supervisor/blob/main/supervisor/mounts/validate.py#L32C1-L33C1 excludes = from being in the password field. Is there a technical reason for this?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Add network storage mount
2. Use an '=' sign in your password

### Anything in the Supervisor logs that might be useful for us?

```txt
Not required
```

### System Health information

Not required

**Comment by mdegat01** [comment]
What version of supervisor are you running? Please share the [system health information](https://my.home-assistant.io/redirect/system_health/) as requested in the issue template. Or copy and paste the supervisor version from the output of `ha supervisor info` in the CLI.

The line you linked does not apply to username and passwords as of `2023.06.3` (the current beta of supervisor). It used to apply to username and passwords because all mount options had to be passed into a single string like this `opt1=opt1value,opt2=opt2value,...`. This meant `=` and `,` had to be restricted from anything passed in that string. But #4399 fixed that by taking usernames and passwords out of this string and using a separate credential file.

If you are not on the beta channel this will be fixed soon when the current beta goes stable. If you are on the beta channel then please let me know as that means there's still an issue.

**Comment by jourdant** [comment]
## System Information

version | core-2023.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 916.2 GB
disk_used | 10.9 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.6.2), AirCast (3.5.3), ZeroTier One (0.16.3), UniFi Network Application (2.6.0), File editor (5.6.0), Silicon Labs Multiprotocol (2.2.0), Tailscale (0.11.1), Matter Server (4.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 25, 2023 at 12:30 PM
-- | --
current_recorder_run | June 26, 2023 at 3:06 PM
estimated_db_size | 5.15 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by jourdant** [comment]
Appreciate your quick response there - I'm running Supervisor 2023.06.2. I won't move this particular unit onto the beta channel, but I'll give 2023.06.3 a go on another and report back.

**Comment by jourdant** [comment]
Quick update - the UI is no longer blocking the = signs in the password which is great. However I'm now getting a permissions issue which I wonder could be related to any recent changes around escaping characters? I've tried on Windows and Linux hosts to mount using the same details without any issues.

For additional context, the password is a hash of some sort, it can contain + or = as well as standard alphanumeric characters. It is also 88 characters long if that has any bearing on the result too. The Azure Storage Account is configured to accept SMB 2.1, 3.0 and 3.1.1 connections.

I've pasted the log below, but not sure how much help it will be given that it is simply bringing back a permission denied error.

```
Jun 28 13:45:23 homeassistant systemd[1]: Mounting Supervisor cifs mount: azurefiles...
Jun 28 13:45:23 homeassistant kernel: CIFS: Attempting to mount \\<my_account_name>.file.core.windows.net\homeassistant-yellow
Jun 28 13:45:23 homeassistant kernel: CIFS: Status code returned 0xc000006d STATUS_LOGON_FAILURE
Jun 28 13:45:23 homeassistant kernel: CIFS: VFS: \\<my_account_name>.file.core.windows.net Send error in SessSetup = -13
Jun 28 13:45:23 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -13
Jun 28 13:45:23 homeassistant mount[620094]: mount error(13): Permission denied
Jun 28 13:45:23 homeassistant mount[620094]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 28 13:45:23 homeassistant systemd[1]: mnt-data-supervisor-mounts-azurefiles.mount: Mount process exited, code=exited, status=32/n/a
Jun 28 13:45:23 homeassistant systemd[1]: mnt-data-supervisor-mounts-azurefiles.mount: Failed with result 'exit-code'.
Jun 28 13:45:23 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: azurefiles.
```

**Comment by Toolmaster30** [comment]
The update to Supervisor 2023.06.4 came today and since then I can no longer connect a network drive.

I can offer these logs:
​

`Jun 29 13:16:00 media-server systemd[1]: Mounting usr-share-hassio-mounts-Backup_Folder.mount - Supervisor cifs mount: Backup_Folder...
Jun 29 13:16:00 media-server mount[4724]: mount: /usr/share/hassio/mounts/Backup_Folder: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
Jun 29 13:16:00 media-server mount[4724]:        dmesg(1) may have more information after failed mount system call.
Jun 29 13:16:00 media-server systemd[1]: usr-share-hassio-mounts-Backup_Folder.mount: Mount process exited, code=exited, status=32/n/a
Jun 29 13:16:00 media-server systemd[1]: usr-share-hassio-mounts-Backup_Folder.mount: Failed with result 'exit-code'.
Jun 29 13:16:00 media-server systemd[1]: Failed to mount usr-share-hassio-mounts-Backup_Folder.mount - Supervisor cifs mount: Backup_Folder.
Jun 29 13:16:00 media-server kernel: CIFS: Attempting to mount \\192.168.178.2\Home-Backup
Jun 29 13:16:00 media-server kernel: CIFS: VFS: No username specified`


`23-06-29 13:15:59 ERROR (MainThread) [supervisor.mounts.mount] Mounting Backup_Folder did not succeed. Check host logs for errors from mount or systemd unit usr-share-hassio-mounts-Backup_Folder.mount for details.`

**Comment by jourdant** [comment]
Just to add on to this, I have also updated Supervisor to 2023.06.4 and getting a new error with the Auto protocol option. The error banner states: ```not a valid value for dictionary value @ data['version']. Got 'auto'```.

**Comment by dgrove** [comment]
To add on, network storage for me stopped working with 2023.06.3 . I had moved my media storage to an nfs mount (using an IP address, not a server name). Frigate began seg faulting and exiting as soon as the update to 2023.06.3 occurred. Nothing else changed.

**Comment by mdegat01** [comment]
@jourdant this was a frontend issue, https://github.com/home-assistant/frontend/pull/17148 . This and one other unrelated frontend issue was the reason for the recent quick version bumps in supervisor (`2023.07.0` and `2023.07.1`) since some of the frontend is shipped as part of supervisor. You should not have that issue anymore. If you do, please report an issue in frontend.

Although on a side note, no matter which version of supervisor you're currently on you can always get around this in the CLI as this was only a UI bug. Type `ha mounts add -h` to see the options for adding a mount that way.

**Comment by mdegat01** [comment]
> I've pasted the log below, but not sure how much help it will be given that it is simply bringing back a permission denied error.

@jourdant do you have host access by any chance? If so can you take a look at the file `/mnt/data/supervisor/.mounts_credentials/azurefiles` and confirm it looks right? It should have this form:
```
username=<username>
password=<password>
```
If no then that's the issue and I'll have to dig into why. If you could tell me what looks wrong with it without revealing the credentials that would help. Or I am `centralcommand` on discord if you feel more comfortable DM'ing me info there.

If that file does look right then must be something else going on. With host access you can try to mount directly into the `/tmp` folder to test that it works, should be something like this:
```
mount -t cifs -o "credentials=/mnt/data/supervisor/.mounts_credentials/azurefiles" \\<my_account_name>.file.core.windows.net\homeassistant-yellow /tmp/azurefiles
```

Alternatively (or in addition to the above) if anyone can sign up for this azure service drop a link where and I'll sign up and try to reproduce on my own.

**Comment by jourdant** [comment]
@mdegat01 I upgraded to official channel 2023.07.1 and tried to load the credentials again. UI issue no longer seen but no dice connecting. I've checked the /mnt/data/supervisor/.mounts_credentials/ directory on the host and I'm not seeing anything in the folder.

While I was on the host, I ran:
```mount -t cifs //<storage_account_name>.file.core.windows.net/homeassistant-yellow /tmp/azurefiles -o username=<storage_account_name>,password="<storage_account_key_1>"```.

This did mount successfully and I was able to write a text file to the directory and see it reflected on other devices that had the same mount point connected. The fact that its working directly with the mount command makes me think there is something going on with how the credentials file is being checked.

Any ideas what to check next? I'm happy to provide you a sample endpoint to connect to if you'd like to give it a go too. Feels like we're getting close now though.

**Comment by jourdant** [comment]
Further update - I've upgraded to 2023.07.1 now and done the test again. I'm not sure if this is because I had previously done the mount on the commandline and some residual config was left over - or its actually now fixed. But it works!

<img width="1494" alt="Screenshot 2023-07-07 at 11 36 27 AM" src="https://github.com/home-assistant/supervisor/assets/230794/928fcb1c-5ec6-40b0-9be2-7cf7f61406da">

I am now able to successfully send backups to my Azure Blob Storage Account as an off-site backup for basically no cost and it's extremely easy to configure. I'll do a quick write-up for this on my blog for others who are trying to do this. 

Thanks for your help @mdegat01.

**Comment by jourdant** [comment]
One last comment to round this out - I've tried this on another device that is freshly upgraded to 2023.07.1 with no prior manual mounts in place. Everything works perfectly as it should 🙂
