### ISSUE TITLE
can't update from 2023.06.3 

### ISSUE THREAD

**Issue by motogon** [home-assistant/supervisor#4426]
### Describe the issue you are experiencing

The update does not work on version 2023.06.3 
ubuntu - docker

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Ubuntu

### Steps to reproduce the issue

1. Setup
2. Home Assistant Supervisor Update

### Anything in the Supervisor logs that might be useful for us?

```txt
23-07-06 15:13:35 INFO (MainThread) [__main__] Initializing Supervisor setup
23-07-06 18:13:35 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64
23-07-06 18:13:35 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2023.06.3
23-07-06 18:13:35 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-06 18:13:35 INFO (SyncWorker_1) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/amd64-hassio-supervisor:2023.07.1']
23-07-06 18:13:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE

23-07-06 18:13:35 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported job conditions settings. (more-info: https://www.home-assistant.io/more-info/unsupported/job_conditions)

23-07-06 18:13:35 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker logging driver json-file is not supported!

23-07-06 18:13:35 WARNING (MainThread) [supervisor.resolution.evaluations.base] The configuration of Docker is not supported (more-info: https://www.home-assistant.io/more-info/unsupported/docker_configuration)

23-07-06 18:13:35 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-07-06 18:13:35 ERROR (MainThread) [supervisor.core] Update '2023.07.1' of Supervisor '2023.06.3' failed!
23-07-06 18:13:35 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.UPDATE_ROLLBACK - ContextType.SUPERVISOR / None

23-07-06 18:13:35 INFO (MainThread) [__main__] Setting up Supervisor
```

### System Health information

[HA-System.txt](https://github.com/home-assistant/supervisor/files/11969888/HA-System.txt)

### Supervisor diagnostics

[config_entry-hassio-f27d146aaf65ffd814aa0470985e6579.json.txt](https://github.com/home-assistant/supervisor/files/11969756/config_entry-hassio-f27d146aaf65ffd814aa0470985e6579.json.txt)

**Comment by mdegat01** [comment]
Supervised on Ubuntu is not supported. The only supported OS for running supervised is Debian, not a derivative of Debian. This is very likely related to why you are having issues with your docker configuration, as the log says docker is not set up properly for Supervisor on your system.

Since you are running unsupported the suggested solution of re-running the installation script won't work for you as it only runs on supported systems. You will need to make the changes suggested [here](https://www.home-assistant.io/more-info/unsupported/docker_configuration#the-solution) manually. There may be other changes required as well to make things functional on Ubuntu that you'll have to figure out on your own.

My advice would be to migrate to a supported system. If you want to continue to battle with your current system to get it work you can ask for advice on [the forum](https://community.home-assistant.io/)
