### ISSUE TITLE
Can't Restore my backup on a new machine

### ISSUE THREAD

**Issue by twanjaarsveld** [home-assistant/supervisor#4806]
### Describe the issue you are experiencing

After wanting to move to a different system i installed HA OS on it and made a backup from my up-to-date system
but it doesn't seem to work, i know its possible because i did it many times before.
![Screenshot 2024-01-09 204741](https://github.com/home-assistant/supervisor/assets/72700125/b9b574b9-906b-467b-853c-0b3c4ba61a86)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.Make a backup (mine was 1.8gb big)
2.install the latest Home Assistant OS on a new machine 
3.after it installs select (restore from backup)
4. wait for many hours as it wont do anything

### Anything in the Supervisor logs that might be useful for us?

```txt
Started busy box
```

### System Health information

Using home assistant observer it shows everything to be healty

**Comment by jennettwheeler** [comment]
FYI, I found 2023.12.1 by updating the supervisor to use beta channel. Then my restore worked. Obviously I don’t know if you’re seeing the same thing as I was, because you didn’t put any logs up

**Comment by codyc1515** [comment]
I was going to post this, so thanks for the reminder. Here is my write-up for reproducing this issue:

1. Tried to restore full and partial backups but it kept not succeeding
2. Upload to HA was succesful (no errors)
3. Checked the request to http://homeassistant.local:8123/api/hassio/backups/be7a8382/restore/full - this gave a response of:
```
{
	"result": "error",
	"message": "Unknown error, see supervisor"
}
```
5. I installed clean HA, set-up with defaults and attempted to restore, got the following error:
`24-01-12 20:42:12 ERROR (MainThread) [supervisor.backups.manager] Backup was made on supervisor version 2023.12.1, can't restore on 2023.12.0. Must update supervisor first.
`
7. Modified the backups.json file within the tar.gz file to have a supervisor value of 2023.12.0 (instead of 2023.12.1).

8. I was then able to re-attempt a restore with no issues.

It is apparent that there is actually three distinct issues going on here - each of which will need fixing separately:

1. **No display of errors during restore**: The exception at the point of restoring was uncaught. This caused the restore to fail without any notice to the user that it was failed. You can tell the restore process failed visually by refreshing the page and seeing that you are again given the option to upload a backup file (suggesting it did not restore). That said, we should add a check immediately after restore submission upload.
2. **Unknown error shown in console**: Even if the exception was caught and displayed to the user, it simply would have said the error was unknown which is not something a user can do anything with. This is a problem as my Pi runs headless, so I was unable to get the supervisor logs and instead needed to create a blank install then restore from there and check the browser console for errors.
3. **Supervisor is not upgraded automatically**: The actual error is that when there is a newer version of the supervisor identified as being required following a backup upload but the onboarding process does not download the new supervisor or otherwise proceed with the restore process. I think this is meant to happen under the hood but in practise it doesn't seem to. If not, it should at least prompt the user that a supervisor upgrade and reboot is required first.

**Comment by Baxxy13** [comment]
The problem here is that backups from newer supervisors cannot be installed on older supervisors. This is fine so far.
```
Jan 14 09:23:38 homeassistant hassio_supervisor[570]: 24-01-14 10:23:38 INFO (MainThread) [supervisor.backups.manager] Successfully imported 28fde29b
Jan 14 09:23:47 homeassistant hassio_supervisor[570]: 24-01-14 10:23:47 ERROR (MainThread) [supervisor.backups.manager] Backup was made on supervisor version 2023.12.1, can't restore on 2023.12.0. Must update supervisor first.
```

In my case i need supervisor 2023.12.1 which should be installed automatically but is not installed automatically.
```
# ha supervisor update
Error: No supervisor update available - 2023.12.0
```
If I switch to the beta channel (mentioned by @jennettwheeler ), the required supervisor can be installed and then the backup can be restored.
```
# ha supervisor options --channel=beta
Command completed successfully.
# ha supervisor reload
Command completed successfully.
# ha supervisor update
Command completed successfully.
```
```
Jan 14 09:29:24 homeassistant hassio_supervisor[570]: 24-01-14 10:29:24 WARNING (MainThread) [supervisor.backups.manager] Backup 28fde29b already exists! overwriting
Jan 14 09:29:24 homeassistant hassio_supervisor[570]: 24-01-14 10:29:24 INFO (MainThread) [supervisor.backups.manager] Removed backup file 28fde29b
Jan 14 09:29:24 homeassistant hassio_supervisor[570]: 24-01-14 10:29:24 INFO (MainThread) [supervisor.backups.manager] Successfully imported 28fde29b
Jan 14 09:29:34 homeassistant hassio_supervisor[570]: 24-01-14 10:29:34 INFO (MainThread) [supervisor.backups.manager] Full-Restore 28fde29b start
.
.
.
Jan 14 09:37:01 homeassistant hassio_supervisor[570]: 24-01-14 10:37:01 INFO (MainThread) [supervisor.backups.manager] Full-Restore 28fde29b done
```

So the main problem seems that needed supervisor 2023.12.1 can't be find/installed automatically.

**Comment by codyc1515** [comment]
That’s my understanding too, although for whatever reason I don’t think it showed till I went on beta channel.

**Comment by agners** [comment]
I *think* PR #4791 should handle this more gracefully (as in, it should print a sensible message during onboarding). However, the problem remains that we disallow restoring a backup from the beta channel.

/cc @mdegat01 I've hinted at that problem during review. I think it mostly appearing now because we had quite some folks having to reinstall due to update problems on Raspberry Pi 5 (which initially required people to be on beta/dev channel) :cry:

**Comment by codyc1515** [comment]
Is it expected that Supervisor 2023.12.1 is only available through beta? I understand not wanting to permit down grades 100% - I experienced issues with the schema mapping when I changed the version in my backup file. But surely we should permit upgrades?

**Comment by codyc1515** [comment]
Yep, looks like 2023.12.0 is the [stable version](https://github.com/home-assistant/version/blob/master/stable.json) (not 2023.12.1). The changes made in #4791 look like what I was going to tackle, so I think this issue will be solved with the next beta (alongside my other changes in https://github.com/home-assistant/frontend/pull/19389).

**Comment by codyc1515** [comment]
This should be fixed now.
