### ISSUE TITLE
journalctl -xb shows `hassio_supervisor` lines in red though they are `INFO`.

### ISSUE THREAD

**Issue by dothebart** [home-assistant/supervisor#4948]
### Describe the issue you are experiencing

`journalctl -xb` is used to browse the system messages.
Its colour coded to ease Browsing. 
However, certain `hassio_supervisor` lines in read though they are `INFO`:
i.e.:
```
Mar 07 20:29:01 qube hassio_supervisor[1422]: 24-03-07 20:29:01 INFO (MainThread) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2024.02.1 - 172.30.32.5
Mar 07 20:29:01 qube hassio_supervisor[1422]: 24-03-07 20:29:01 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2023.06.2
Mar 07 20:29:01 qube hassio_supervisor[1422]: 24-03-07 20:29:01 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
Mar 07 20:29:01 qube hassio_supervisor[1422]: 24-03-07 20:29:01 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_dns application
Mar 07 20:29:01 qube hassio_cli[1422]: s6-rc: info: service s6rc-oneshot-runner: starting
Mar 07 20:29:01 qube hassio_cli[1422]: s6-rc: info: service s6rc-oneshot-runner successfully started
Mar 07 20:29:01 qube hassio_cli[1422]: s6-rc: info: service fix-attrs: starting
```
this obstructs the view to real errors. Please don't use red for these. 

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

`journalctl -xb` is used to browse the system messages.

Lines that should continue to be red: 
```
Mar 07 20:29:16 qube hassio_supervisor[1422]: 24-03-07 20:29:16 ERROR (MainThread) [supervisor.store.git] Integrity check on /data/addons/git/5c53de3b failed: Cmd('git') failed due to: exit code(128)
Mar 07 20:29:16 qube hassio_supervisor[1422]:   cmdline: git fsck
Mar 07 20:29:16 qube hassio_supervisor[1422]:   stderr: 'fatal: detected dubious ownership in repository at '/data/addons/git/5c53de3b'
Mar 07 20:29:16 qube hassio_supervisor[1422]: To add an exception for this directory, call:
Mar 07 20:29:16 qube hassio_supervisor[1422]: 
Mar 07 20:29:16 qube hassio_supervisor[1422]:         git config --global --add safe.directory /data/addons/git/5c53de3b'.
```

**Comment by agners** [comment]
By default `journalctl` formats logs based on what standard stream the message originated from (stderr/stdout). The Supervisor logs uses Python logging default basic configuration (see [supervisor/bootstrap.py:258](https://github.com/home-assistant/supervisor/blob/2024.03.0/supervisor/bootstrap.py#L258) and [basicConfig Python docs](https://docs.python.org/3/library/logging.html#logging.basicConfig)) which uses stderr by default. `journalctl` formats stderr red by default :cry: 

That said, Supervisor actually uses colored logger, which adds colors to the log messages based on the log level. However, `journalctl` seems to filter out/override those by default (from what I understand journalctl processes log entries "plain text" by default).

Since we also include time stamps inline, I recommend looking at Home Assistant Supervisor logs raw, e.g. using `ha supervisor logs` or `journalctl -xb -t hassio_supervisor -o cat`. 

Where do you run `journalctl -xb` from? :thinking: 

FWIW, we are also working on extending the logging functionality so that the frontend becomes more capable.

/cc @sairon

**Comment by agners** [comment]
> I was launching hass from systemd at that time, hence its logging was also part of the game.

Supervised installation launch the Supervisor by default from systemd. But more importantly, we use the systemd-journald logging backend for all containers. So in the end, all output land in systemd-journald ultimately.

> I did not find all Information just some obscure "there are more errors" in the UI, hence I started looking at journalctl.

You probably hit one of the "Unkown error, see supervisor logs" errors? If so, you can access the Supervisor logs from Settings -> System -> Logs then select Supervisor in the top right drop down (I think this needs advanced mode). In that view the logs are colored.

Now the log view does not offer as much history as journalctl does. And we are working improving this. But the idea is essentially to use this to view logs.

Since we can't really do anything about the coloring of the logs on systemd-journald side, I am going to close this.
