### ISSUE TITLE
Can't fetch Whoami data: Cannot connect to host services.home-assistant.io:443 ssl:default

### ISSUE THREAD

**Issue by carusoray** [home-assistant/supervisor#4987]
### Describe the issue you are experiencing

New install on Raspberry PI 4. 
Used Raspberry Pi Imager. 
OS Version: Home. Assistant OS 12.1
Home Assistant Core: landing page

During setup, I go to the new system page http://homeassitant.local:8123 and see:

"Error installing Home Assistant"

The first related warning is:

23-04-04 10:58:29 WARNING (MainThread) [supervisor.utils.whoami] Can't fetch Whoami data: Cannot connect to host services.home-assistant.io:443 ssl:default [Try again]

System has internet connectivity and is able to ping and pinged. 
System is attempting to connect to internal DNS server. 

Logs attached. 

[logs.txt](https://github.com/home-assistant/supervisor/files/14781403/logs.txt)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Create a new install image SSD using Raspberry PI Imager.
2. Boot the system.
3. Wait for the failure. 
4. Cry...

### Anything in the Supervisor logs that might be useful for us?

```txt
I can't get this to page because the system will not install.
```

### System Health information

I can't get this to page because the system will not install.

**Comment by moddroid94** [comment]
Hi @carusoray ,

Seems like a bug that has been around for a while, there are some solutions in https://github.com/home-assistant/operating-system/issues/1636 and https://community.home-assistant.io/t/error-ha-installation-no-supervisor-internet-connection/674192
 
in short you can check if the IP and DNS server of the Pi get correctly assigned by the modem, it can be a mismatch between host date and actual date, it can be that the Pi gets an IPv6 DNS instead of an IPv4 one.

have you tried connecting a monitor to the Pi and see the console output? that way you can check the network configuration and maybe there are more info on the error.

hope it helps :)
