### ISSUE TITLE
Remove stalebot

### ISSUE THREAD

**Issue by jamesgeddes** [home-assistant/supervisor#5073]
### Describe the issue you are experiencing

[Stalebot is bad](https://drewdevault.com/2021/10/26/stalebot.html). Let's remove it. There is no shame in having many open issues.

**Comment by agners** [comment]
> [Stalebot is bad](https://drewdevault.com/2021/10/26/stalebot.html). Let's remove it. There is no shame in having many open issues.

Well, not entirely agreeing with this rant, e.g.

> Let me offer you a different way of thinking about issues: a place for motivated users to collaborate on narrowing down the problem and planning a potential fix

I agree to think about issues that way! But how does marking stale prevent users from discussing and collaborating? I think the screenshot shows that conversation is limited to contributors immediately after it received the stale label/gets closed. That is that particular implementation of stale bot. In our implementation you can continue to collaborate once marked stale. And please feel free to continue discuss and collaborate on stale issues! Ping if you feel it went stale but shouldn't. I do monitor comments, and remove the stale label and add the pinned label, which makes them not go stale forever, if appropriate. 

That said, we do lock issues after a longer period as well. Mainly to prevent folks from reviving long dead issues with a simple "me too" comment. If the same issue really appears on the latest version, it is much better for us to get a new, full report with all the logs and system information. This new issue should have a link to the old issue saying it looks like this. This then might help to find a pattern.

But there are very good reasons to mark things as stale. Sometimes it is third party services which were temporarily down which caused issue (e.g. #4987 might have been such a case). Or people had a very specific setup and ultimately moved on. Sometimes the bug got fixed by some other change, but the developer didn't realize (and hence did not close) and the author did also not come back to close the issue. We also have many issues where I asked for more clarification where folks just did not respond. What is the value of keeping such an issue open forever?

With stale bot, open issues are also the ones we can consider as alive.
